/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.Course.CourseList;
import Business.ProfessorList;
import Business.ProfessorLoginList;
import Business.Student;
import Business.StudentList;
import Business.StudentLogin;
import Business.StudentLoginList;
import Business.ThirdPartyList;

/**
 *
 * @author metla
 */
public class StudentCatalogPanel extends javax.swing.JPanel {
    
    StudentList studentList;
    StudentLoginList studentLoginList;
    MainJFrame frame;
    ProfessorList professorList;
    ProfessorLoginList professorLoginList;
    CourseList courseList;
    ThirdPartyList thirdPartyList;
    JPanel userProcessContainer;
    

    /**
     * Creates new form StudentCatalog
     * @param studentList
     * @param studentLoginList
     */
    public StudentCatalogPanel(JPanel userProcessContainer, ProfessorList professorList, ProfessorLoginList professorLoginList, CourseList courseList,StudentList studentList, StudentLoginList studentLoginList, ThirdPartyList thirdPartyList) {
        initComponents();
        this.professorList = professorList;
        this.professorLoginList = professorLoginList;
        this.courseList = courseList;
        this.studentList= studentList;
        this.studentLoginList= studentLoginList;
        this.thirdPartyList = thirdPartyList;
        this.userProcessContainer = userProcessContainer;
        populateStudTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStudentCatalog = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStud = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblStudentDetails = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnAddStud = new javax.swing.JButton();
        lblStudentId = new javax.swing.JLabel();
        lblStudentName = new javax.swing.JLabel();
        lbStudentEmail = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        txtStudentName = new javax.swing.JTextField();
        txtStudentEmail = new javax.swing.JTextField();
        lblStudentUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtStudentUserName = new javax.swing.JTextField();
        txtStudentPassword = new javax.swing.JTextField();

        lblStudentCatalog.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblStudentCatalog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStudentCatalog.setText("STUDENT CATALOG");

        tblStud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student Id", "User Name", "Password", "Student Name", "Email"
            }
        ));
        jScrollPane1.setViewportView(tblStud);

        btnUpdate.setText("UPDATE STUDENT");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE STUDENT");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblStudentDetails.setText("STUDENT DETAILS:");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAddStud.setText("ADD STUDENT");
        btnAddStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudActionPerformed(evt);
            }
        });

        lblStudentId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentId.setText("Student Id:");

        lblStudentName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentName.setText("Student Name:");

        lbStudentEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbStudentEmail.setText("Email:");

        lblStudentUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentUsername.setText(" Username:");

        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPassword.setText("Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblStudentCatalog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblStudentDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStudentUsername)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblStudentId)
                                .addComponent(lbStudentEmail)
                                .addComponent(lblStudentName))
                            .addComponent(lblPassword))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtStudentUserName)
                            .addComponent(txtStudentName)
                            .addComponent(txtStudentEmail)
                            .addComponent(txtStudentId, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtStudentPassword))
                        .addGap(262, 262, 262))))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnAddStud)
                .addGap(131, 131, 131)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addGap(40, 40, 40))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddStud, btnDelete, btnUpdate});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbStudentEmail, lblStudentId, lblStudentName});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtStudentEmail, txtStudentId, txtStudentName, txtStudentPassword, txtStudentUserName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblStudentCatalog)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStudentDetails)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentId)
                    .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStudentEmail)
                    .addComponent(txtStudentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentUsername)
                    .addComponent(txtStudentUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtStudentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddStud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddStud, btnDelete, btnUpdate});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbStudentEmail, lblStudentId, lblStudentName});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtStudentEmail, txtStudentId, txtStudentName, txtStudentPassword, txtStudentUserName});

    }// </editor-fold>//GEN-END:initComponents
    private void populateStudTable() {
    DefaultTableModel model = (DefaultTableModel) tblStud.getModel();
    model.setRowCount(0);
    
    for (int i = 0; i < studentList.getStudentList().size(); i++){
        Student s = studentList.getStudentList().get(i);
        StudentLogin sl = studentLoginList.getStudentLoginList().get(i);        
        Object[] row = new Object[5];
        row[0] = s; 
        row[1] = sl;
        row[2] = sl.getStudentPassword();
        row[3] = s.getStudentName();
        row[4] = s.getStudentEmail();

        model.addRow(row);
    }
}
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblStud.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblStud.getModel();
        Student selectedStudent = (Student) model.getValueAt(selectedRowIndex, 0);
        StudentLogin selectedStudentLogin = (StudentLogin) model.getValueAt(selectedRowIndex, 1);
        studentList.deleteStudent(selectedStudent);
        JOptionPane.showMessageDialog(this, "Student deleted.");
        studentLoginList.deleteStudentLogin(selectedStudentLogin);
        populateStudTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudActionPerformed
        // TODO add your handling code here:
         String studentID = txtStudentId.getText();
         String studentName = txtStudentName.getText();
         String studentEmail = txtStudentEmail.getText();
         String studentUsername = txtStudentUserName.getText();
         String studentPassword = txtStudentPassword.getText();
         
         Student stud= studentList.addNewStudent();
         StudentLogin studlogin= studentLoginList.addNewStudentLogin();
         
         stud.setStudentName(studentName);
         stud.setStudentID(studentID);
         stud.setStudentEmail(studentEmail);
         studlogin.setStudentUsername(studentUsername);
         studlogin.setStudentPassword(studentPassword);
         
        populateStudTable();
              
        JOptionPane.showMessageDialog(this, "Student added");
        
    }//GEN-LAST:event_btnAddStudActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String studentID = txtStudentId.getText();
         String studentName = txtStudentName.getText();
         String studentEmail = txtStudentEmail.getText();
         String studentUsername = txtStudentUserName.getText();
         String studentPassword = txtStudentPassword.getText();
        DefaultTableModel model= (DefaultTableModel) tblStud.getModel();
        int selectedRowIndex = tblStud.getSelectedRow();
        Student selectedStudent = (Student) model.getValueAt(selectedRowIndex, 0);
        StudentLogin selectedStudentLogin = (StudentLogin) model.getValueAt(selectedRowIndex, 1);
        selectedStudent.setStudentName(studentName);
        selectedStudent.setStudentID(studentID);
        selectedStudent.setStudentEmail(studentEmail);
        selectedStudentLogin.setStudentUsername(studentUsername);
        selectedStudentLogin.setStudentPassword(studentPassword);
        populateStudTable();
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStud;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbStudentEmail;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblStudentCatalog;
    private javax.swing.JLabel lblStudentDetails;
    private javax.swing.JLabel lblStudentId;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblStudentUsername;
    private javax.swing.JTable tblStud;
    private javax.swing.JTextField txtStudentEmail;
    private javax.swing.JTextField txtStudentId;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JTextField txtStudentPassword;
    private javax.swing.JTextField txtStudentUserName;
    // End of variables declaration//GEN-END:variables

    public DefaultTableModel getStudentTable(){
        DefaultTableModel model = (DefaultTableModel) tblStud.getModel();
        return model;
    }

}
