/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.Course.CourseList;
import Business.ProfessorList;
import Business.ProfessorLoginList;
import Business.StudentList;
import Business.StudentLoginList;
import Business.ThirdParty;
import Business.ThirdPartyList;

/**
 *
 * @author metla
 */
public class ThirdPartyCatalogPanel extends javax.swing.JPanel {

    /**
     * Creates new form ThirdPartyCertification
     */
    MainJFrame frame;
    ProfessorList professorList;
    ProfessorLoginList professorLoginList;
    CourseList courseList;
    StudentList studentList;
    StudentLoginList studentLoginList;
    ThirdPartyList thirdPartyList;
    JPanel userProcessContainer;
    
    public ThirdPartyCatalogPanel(JPanel userProcessContainer, ProfessorList professorList, ProfessorLoginList professorLoginList, CourseList courseList, StudentList studentList, StudentLoginList studentLoginList, ThirdPartyList thirdPartyList) {
        initComponents();
        this.professorList = professorList;
        this.professorLoginList = professorLoginList;
        this.courseList = courseList;
        this.studentList = studentList;
        this.studentLoginList = studentLoginList;
        this.thirdPartyList = thirdPartyList;
        this.userProcessContainer= userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCertificationAuth = new javax.swing.JLabel();
        lblCADetails = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAuthority = new javax.swing.JTable();
        btnAddAuth = new javax.swing.JButton();
        btnDeleteAuth = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtAuth = new javax.swing.JTextField();

        lblCertificationAuth.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCertificationAuth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCertificationAuth.setText("CERTIFICATION AUTHORITY");

        lblCADetails.setText("Certification Authority Details:");

        tblAuthority.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Authority Name"
            }
        ));
        jScrollPane1.setViewportView(tblAuthority);

        btnAddAuth.setText("Add Authority");
        btnAddAuth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAuthActionPerformed(evt);
            }
        });

        btnDeleteAuth.setText("Delete Authority");
        btnDeleteAuth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAuthActionPerformed(evt);
            }
        });

        btnBack.setText("<< BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCertificationAuth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCADetails, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBack))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnDeleteAuth)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAddAuth)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtAuth)))))
                        .addGap(167, 167, 167)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCertificationAuth, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCADetails))
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAuth)
                    .addComponent(txtAuth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDeleteAuth)
                .addGap(98, 98, 98))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddAuthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAuthActionPerformed
        // TODO add your handling code here:
        String thirdParty = txtAuth.getText();
        ThirdParty tp = thirdPartyList.addThirdParty();
        
        tp.setAuthorityName(thirdParty);
        populateAuthTable();
              
        JOptionPane.showMessageDialog(this, "Third Party added");
        
    }//GEN-LAST:event_btnAddAuthActionPerformed

    private void btnDeleteAuthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAuthActionPerformed
        // TODO add your handling code here: 
        int selectedRowIndex = tblAuthority.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblAuthority.getModel();
        ThirdParty tp = (ThirdParty) model.getValueAt(selectedRowIndex, 0);
        thirdPartyList.deleteThirdParty(tp);
        
        JOptionPane.showMessageDialog(this, "Third Party deleted.");
        populateAuthTable();
    }//GEN-LAST:event_btnDeleteAuthActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAuth;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteAuth;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCADetails;
    private javax.swing.JLabel lblCertificationAuth;
    private javax.swing.JTable tblAuthority;
    private javax.swing.JTextField txtAuth;
    // End of variables declaration//GEN-END:variables

    private void populateAuthTable() {
    DefaultTableModel model = (DefaultTableModel) tblAuthority.getModel();
    model.setRowCount(0);

    for (int i = 0; i < thirdPartyList.getThirdPartyList().size(); i++){
        ThirdParty t = thirdPartyList.getThirdPartyList().get(i);
        
        Object[] row = new Object[1];
        row[0] = t; 
        
        model.addRow(row);
    }
   }
}
