/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.RoleSelection.Professor;

import Business.Course.Course;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.Course.CourseList;
import Business.Professor.ProfessorList;
import Business.ProfessorLogin.ProfessorLoginList;
import Business.Student.StudentList;
import Business.StudentLogin.StudentLoginList;
import Business.ThirdParty.ThirdPartyList;
import Business.Student.Student;
import UserInterface.RoleSelection.MainJFrame;
import java.util.HashMap;
import java.util.List;

/**
 *
 * @author kamuni.saheeshna
 */
public class ProfessorStudentListPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorStudentListPanel
     */
    ProfessorList professorList;
    ProfessorLoginList professorLoginList;
    MainJFrame frame;
    CourseList courseList;
    StudentList studentList;
    StudentLoginList studentLoginList;
    ThirdPartyList thirdPartyList;
    JPanel userProcessContainer;
     HashMap<String, List<Course>> studentCour;
    
    public ProfessorStudentListPanel(JPanel userProcessContainer, ProfessorList professorList, ProfessorLoginList professorLoginList, CourseList courseList,  StudentList studentList, StudentLoginList studentLoginList,ThirdPartyList thirdPartyList,  HashMap<String, List<Course>> studentCour ) {
        initComponents();
        
        this.professorList = professorList;
        this.professorLoginList = professorLoginList;
        this.courseList = courseList;
        this.studentList =studentList;
        this.studentLoginList = studentLoginList;  
        this.thirdPartyList = thirdPartyList;
        this.userProcessContainer = userProcessContainer;
        this.studentCour = studentCour;
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEnrolledStudentTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnrolledList = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        lblGPA = new javax.swing.JLabel();
        txtGPA = new javax.swing.JTextField();
        btnGrade = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 153));

        lblEnrolledStudentTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEnrolledStudentTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnrolledStudentTitle.setText("Enrolled Students");

        tblEnrolledList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Student Name", "Course Name"
            }
        ));
        jScrollPane1.setViewportView(tblEnrolledList);

        btnBack.setBackground(new java.awt.Color(204, 204, 255));
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblGPA.setText("Student CGPA:");

        txtGPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGPAActionPerformed(evt);
            }
        });

        btnGrade.setBackground(new java.awt.Color(204, 204, 255));
        btnGrade.setText("Grade");
        btnGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGPA)
                .addGap(18, 18, 18)
                .addComponent(txtGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGrade)
                .addGap(97, 97, 97))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblEnrolledStudentTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblEnrolledStudentTitle)
                .addGap(4, 4, 4)
                .addComponent(btnBack)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGPA)
                    .addComponent(txtGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrade))
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtGPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGPAActionPerformed

    private void btnGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradeActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblEnrolledList.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select the student to grade.");
            return;
        }
        
        //tblEnrolledList.setValueAt(txtGPA.getText(),selectedRowIndex , 3);
        
      
String selectedStudentName = (String) tblEnrolledList.getValueAt(selectedRowIndex, 0);
System.out.println("selectedStudName "+ selectedStudentName);
List<Course> coursesTaken = studentCour.get(selectedStudentName);

        
        
if (coursesTaken != null && !coursesTaken.isEmpty()) {
    Student s = studentList.searchStudentName(selectedStudentName);
    s.setGPA(txtGPA.getText());

} else {
    
    JOptionPane.showMessageDialog(this, "Student not found in the enrolled list.");
}

    }//GEN-LAST:event_btnGradeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGrade;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnrolledStudentTitle;
    private javax.swing.JLabel lblGPA;
    private javax.swing.JTable tblEnrolledList;
    private javax.swing.JTextField txtGPA;
    // End of variables declaration//GEN-END:variables

  
    
    public DefaultTableModel getEnrolledStu(){
        DefaultTableModel model = (DefaultTableModel) tblEnrolledList.getModel();
        return model;
    }
    
    
}
