/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HashingPassword;
import model.LoginCredentials;
import model.LoginCredentialsList;
import model.Password;
import model.PasswordList;
import model.PersonDetails;
import model.PersonDetailsList;

/**
 *
 * @author kamuni.saheeshna
 */
public class AdminOperationsPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminOperationsPanel
     */
    PersonDetailsList personList;
    LoginCredentialsList loginList;
    private int rowCount = -1;
    PasswordList passwordList;

    public AdminOperationsPanel(PersonDetailsList personList, LoginCredentialsList loginList, PasswordList passwordList) {
        initComponents();
        this.personList=personList;
        this.loginList = loginList;
        this.passwordList = passwordList;
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminSplitPane = new javax.swing.JSplitPane();
        adminControlArea = new javax.swing.JPanel();
        btnSignUp = new javax.swing.JButton();
        btnListPeople = new javax.swing.JButton();
        btnUpdateUser = new javax.swing.JButton();
        btnDisbaleUser = new javax.swing.JButton();
        btnCreateUser = new javax.swing.JButton();
        adminWorkArea = new javax.swing.JPanel();
        lblSearchNEUIdTitleA = new javax.swing.JLabel();
        scrollPaneA = new javax.swing.JScrollPane();
        tblSearch = new javax.swing.JTable();
        lblSearchA = new javax.swing.JLabel();
        txtSearchA = new javax.swing.JTextField();
        lblNEUIdA = new javax.swing.JLabel();
        lblFirstNameA = new javax.swing.JLabel();
        lblLastNameA = new javax.swing.JLabel();
        lblGenderA = new javax.swing.JLabel();
        lblDateOfBirthA = new javax.swing.JLabel();
        txtNEUIdA = new javax.swing.JTextField();
        txtFirstNameA = new javax.swing.JTextField();
        txtLastNameA = new javax.swing.JTextField();
        txtGenderA = new javax.swing.JTextField();
        txtDateOfBirthA = new javax.swing.JTextField();
        btnSearchA = new javax.swing.JButton();
        lblAdminOpUsername = new javax.swing.JLabel();
        lblAdminOpPassword = new javax.swing.JLabel();
        txtAdminOpUsername = new javax.swing.JTextField();
        txtAdminOpPassword = new javax.swing.JTextField();
        lblNewUsername = new javax.swing.JLabel();
        txtNewUsername = new javax.swing.JTextField();
        btnNewUsername = new javax.swing.JButton();
        lblNewPassword = new javax.swing.JLabel();
        txtJNewPassword = new javax.swing.JPasswordField();
        lblAdminOperationTitle = new javax.swing.JLabel();
        btnUpdatePassword = new javax.swing.JButton();

        btnSignUp.setText("Add Person");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        btnListPeople.setText("List People");
        btnListPeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListPeopleActionPerformed(evt);
            }
        });

        btnUpdateUser.setText("Update User");
        btnUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserActionPerformed(evt);
            }
        });

        btnDisbaleUser.setText("Disable User");
        btnDisbaleUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisbaleUserActionPerformed(evt);
            }
        });

        btnCreateUser.setText("Create User");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminControlAreaLayout = new javax.swing.GroupLayout(adminControlArea);
        adminControlArea.setLayout(adminControlAreaLayout);
        adminControlAreaLayout.setHorizontalGroup(
            adminControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminControlAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSignUp)
                    .addComponent(btnCreateUser)
                    .addComponent(btnDisbaleUser)
                    .addComponent(btnUpdateUser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        adminControlAreaLayout.setVerticalGroup(
            adminControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminControlAreaLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnSignUp)
                .addGap(18, 18, 18)
                .addComponent(btnListPeople)
                .addGap(18, 18, 18)
                .addComponent(btnCreateUser)
                .addGap(26, 26, 26)
                .addComponent(btnUpdateUser)
                .addGap(26, 26, 26)
                .addComponent(btnDisbaleUser)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        adminSplitPane.setLeftComponent(adminControlArea);

        lblSearchNEUIdTitleA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSearchNEUIdTitleA.setText("Search by NEU ID");

        tblSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NEU Id", "First Name", "Last Name", "Username", "Password", "Enabled"
            }
        ));
        scrollPaneA.setViewportView(tblSearch);

        lblSearchA.setText("Search:");

        lblNEUIdA.setText("NEU ID:");

        lblFirstNameA.setText("First Name:");

        lblLastNameA.setText("Last Name:");

        lblGenderA.setText("Gender:");

        lblDateOfBirthA.setText("Date Of Birth:");

        txtNEUIdA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNEUIdAActionPerformed(evt);
            }
        });

        txtGenderA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderAActionPerformed(evt);
            }
        });

        txtDateOfBirthA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateOfBirthAActionPerformed(evt);
            }
        });

        btnSearchA.setText("Search");
        btnSearchA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAActionPerformed(evt);
            }
        });

        lblAdminOpUsername.setText("Username:");

        lblAdminOpPassword.setText("Password:");

        txtAdminOpUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminOpUsernameActionPerformed(evt);
            }
        });

        lblNewUsername.setText("New Username:");

        txtNewUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewUsernameActionPerformed(evt);
            }
        });

        btnNewUsername.setText("Update Username");
        btnNewUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewUsernameActionPerformed(evt);
            }
        });

        lblNewPassword.setText("New Password:");

        lblAdminOperationTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAdminOperationTitle.setText("Admin Operations");

        btnUpdatePassword.setText("Update Password");
        btnUpdatePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminWorkAreaLayout = new javax.swing.GroupLayout(adminWorkArea);
        adminWorkArea.setLayout(adminWorkAreaLayout);
        adminWorkAreaLayout.setHorizontalGroup(
            adminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminWorkAreaLayout.createSequentialGroup()
                .addGroup(adminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminWorkAreaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(adminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminWorkAreaLayout.createSequentialGroup()
                                .addGroup(adminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLastNameA)
                                    .addComponent(lblFirstNameA)
                                    .addComponent(lblGenderA)
                                    .addComponent(lblDateOfBirthA)
                                    .addComponent(lblNEUIdA)
                                    .addComponent(lblAdminOpUsername)
                                    .addComponent(lblAdminOpPassword))
                                .addGap(32, 32, 32)
                                .addGroup(adminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLastNameA)
                                    .addComponent(txtGenderA)
                                    .addComponent(txtDateOfBirthA)
                                    .addComponent(txtFirstNameA)
                                    .addComponent(txtNEUIdA)
                                    .addComponent(txtAdminOpUsername)
                                    .addComponent(txtAdminOpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(adminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNewPassword)
                                    .addComponent(lblNewUsername))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(adminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(adminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnNewUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnUpdatePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(scrollPaneA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(adminWorkAreaLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblSearchNEUIdTitleA)
                        .addGap(18, 18, 18)
                        .addGroup(adminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAdminOperationTitle)
                            .addGroup(adminWorkAreaLayout.createSequentialGroup()
                                .addComponent(lblSearchA)
                                .addGap(44, 44, 44)
                                .addComponent(txtSearchA, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btnSearchA, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        adminWorkAreaLayout.setVerticalGroup(
            adminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminWorkAreaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblAdminOperationTitle)
                .addGroup(adminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminWorkAreaLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(adminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSearchA)
                            .addComponent(lblSearchNEUIdTitleA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminWorkAreaLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(adminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearchA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchA))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneA, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(adminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNEUIdA)
                    .addComponent(txtNEUIdA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(adminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstNameA)
                    .addComponent(txtFirstNameA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(adminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastNameA)
                    .addComponent(txtLastNameA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(adminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenderA)
                    .addComponent(txtGenderA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(adminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateOfBirthA)
                    .addComponent(txtDateOfBirthA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(adminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminOpUsername)
                    .addComponent(txtAdminOpUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNewUsername)
                    .addComponent(txtNewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewUsername))
                .addGap(11, 11, 11)
                .addGroup(adminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminOpPassword)
                    .addComponent(txtAdminOpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNewPassword)
                    .addComponent(txtJNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdatePassword))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        adminSplitPane.setRightComponent(adminWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminSplitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNEUIdAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNEUIdAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNEUIdAActionPerformed

    private void txtGenderAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderAActionPerformed

    private void txtDateOfBirthAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateOfBirthAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateOfBirthAActionPerformed

    private void btnSearchAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAActionPerformed
        // TODO add your handling code here:
        String inputNEUId = txtSearchA.getText();
        DefaultTableModel model = (DefaultTableModel) tblSearch.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            String neuId = model.getValueAt(i, 0).toString();
            if (neuId.equals(inputNEUId)) {
                rowCount = i;
                break;
            }
        }
        if (rowCount == -1) {
            JOptionPane.showMessageDialog(this, "NEU ID not found.");
            return;
        }
        PersonDetails selectedNEUID = (PersonDetails) model.getValueAt(rowCount, 0);
        txtNEUIdA.setText(String.valueOf(selectedNEUID.getNeuID()));
        txtFirstNameA.setText(selectedNEUID.getFirstName());
        txtLastNameA.setText(selectedNEUID.getLastName());
        txtGenderA.setText(selectedNEUID.getGender());
        txtDateOfBirthA.setText(selectedNEUID.getDateOfBirth());
        
        LoginCredentials selectedUsername = (LoginCredentials) model.getValueAt(rowCount, 3);
        txtAdminOpUsername.setText(selectedUsername.getUserName());
        
        Password selectedPassword = (Password)model.getValueAt(rowCount, 4);
        txtAdminOpPassword.setText(selectedPassword.getPassword());
    }//GEN-LAST:event_btnSearchAActionPerformed

    private void txtAdminOpUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminOpUsernameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtAdminOpUsernameActionPerformed

    private void txtNewUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewUsernameActionPerformed

    private void btnNewUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewUsernameActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblSearch.getModel();
        LoginCredentials selectedUpdate = (LoginCredentials) model.getValueAt(rowCount,3 );    
        selectedUpdate.setUserName(txtNewUsername.getText()); 
        
        JOptionPane.showMessageDialog(this, "Username updated");
        model.setValueAt(selectedUpdate.getUserName(), rowCount, 3);
        populate();
    }//GEN-LAST:event_btnNewUsernameActionPerformed

    private void btnListPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListPeopleActionPerformed
        // TODO add your handling code here:
        ListPeoplePanel listPanel = new ListPeoplePanel(personList, loginList);
        adminSplitPane.setRightComponent(listPanel);
    }//GEN-LAST:event_btnListPeopleActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        SignUpPanel signUpPanel = new SignUpPanel(personList);
        adminSplitPane.setRightComponent(signUpPanel);
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserActionPerformed
        // TODO add your handling code here:
        AdminOperationsPanel panel = new AdminOperationsPanel(personList, loginList, passwordList);
        adminSplitPane.setRightComponent(panel.adminWorkArea);
    }//GEN-LAST:event_btnUpdateUserActionPerformed

    private void btnDisbaleUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisbaleUserActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblSearch.getModel();
        PersonDetails selectedUser = (PersonDetails) model.getValueAt(rowCount, 0);
        LoginCredentials selectedLogin = (LoginCredentials) model.getValueAt(rowCount,3);
        model.setValueAt("False", rowCount, 5);
        personList.deletePerson(selectedUser);
        loginList.deleteCredentials(selectedLogin);
        JOptionPane.showMessageDialog(this, "User has been disabled");
    }//GEN-LAST:event_btnDisbaleUserActionPerformed

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        // TODO add your handling code here:
        CreateUserPanel panel = new CreateUserPanel(personList, loginList, passwordList);
        adminSplitPane.setRightComponent(panel);
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void btnUpdatePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePasswordActionPerformed
        // TODO add your handling code here:  
        DefaultTableModel model = (DefaultTableModel) tblSearch.getModel();   
        Password selectedPassword = (Password) model.getValueAt(rowCount, 4);
        boolean isAlreadyUsed = false;
        char[] inputPasswordChars = txtJNewPassword.getPassword();
        String inputNewInput = new String(inputPasswordChars);     
        String hashPassword = HashingPassword.hashPassword(inputNewInput);
        
        for(Password word : passwordList.getPasswordList()){
            if(hashPassword.equals(word.getHashPassword()) || inputNewInput.equals(word.getPassword())){   
                isAlreadyUsed = true;
                break; 
            } 
        }
        if(isAlreadyUsed){
            JOptionPane.showMessageDialog(this, "You cannot choose a previously used password.");
            return;
        }
            selectedPassword.setHashPassword(hashPassword);
            selectedPassword.setPassword(inputNewInput);
            JOptionPane.showMessageDialog(this, "Password Updated");
            
            for(int i=0; i<passwordList.getPasswordList().size();i++){
            System.out.println("i: "+i+"password: "+ passwordList.getPasswordList().get(i).getPassword());
                }
            model.setValueAt(selectedPassword.getPassword(), rowCount, 4);
            populate();       
    }//GEN-LAST:event_btnUpdatePasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminControlArea;
    private javax.swing.JSplitPane adminSplitPane;
    private javax.swing.JPanel adminWorkArea;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btnDisbaleUser;
    private javax.swing.JButton btnListPeople;
    private javax.swing.JButton btnNewUsername;
    private javax.swing.JButton btnSearchA;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JButton btnUpdatePassword;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JLabel lblAdminOpPassword;
    private javax.swing.JLabel lblAdminOpUsername;
    private javax.swing.JLabel lblAdminOperationTitle;
    private javax.swing.JLabel lblDateOfBirthA;
    private javax.swing.JLabel lblFirstNameA;
    private javax.swing.JLabel lblGenderA;
    private javax.swing.JLabel lblLastNameA;
    private javax.swing.JLabel lblNEUIdA;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JLabel lblNewUsername;
    private javax.swing.JLabel lblSearchA;
    private javax.swing.JLabel lblSearchNEUIdTitleA;
    private javax.swing.JScrollPane scrollPaneA;
    private javax.swing.JTable tblSearch;
    private javax.swing.JTextField txtAdminOpPassword;
    private javax.swing.JTextField txtAdminOpUsername;
    private javax.swing.JTextField txtDateOfBirthA;
    private javax.swing.JTextField txtFirstNameA;
    private javax.swing.JTextField txtGenderA;
    private javax.swing.JPasswordField txtJNewPassword;
    private javax.swing.JTextField txtLastNameA;
    private javax.swing.JTextField txtNEUIdA;
    private javax.swing.JTextField txtNewUsername;
    private javax.swing.JTextField txtSearchA;
    // End of variables declaration//GEN-END:variables

    private void populate() {
        DefaultTableModel model = (DefaultTableModel) tblSearch.getModel();
        model.setRowCount(0);
        Object row[] = new Object[6];
        
        for (int i = 0; i < personList.getPersonList().size(); i++) {   
            PersonDetails p = personList.getPersonList().get(i);
            LoginCredentials l = loginList.getLoginList().get(i);
            Password w = passwordList.getPasswordList().get(i);
            row[0]= p;
            row[1]= p.getFirstName();
            row[2]= p.getLastName();
            row[3]= l;
            row[4]= w;
            row[5]= l.getEnabled();
            model.addRow(row);
        }
    }
    
    public DefaultTableModel getTable(){
        DefaultTableModel model = (DefaultTableModel) tblSearch.getModel();
        return model;
    }   
}
