/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;


import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import model.LoginCredentialsList;
import model.PasswordList;
import model.PersonDetailsList;

/**
 *
 * @author kamuni.saheeshna
 */
public class AdminLogin extends javax.swing.JPanel {

    /**
     * Creates new form AdminLogin
     */
    PersonDetailsList personList;
    LoginCredentialsList loginList;
    PasswordList passwordList;
    MainJFrame frame;
    public AdminLogin(PersonDetailsList personList, LoginCredentialsList loginList, PasswordList passwordList ) {
        initComponents();
        this.personList = personList;
        this.loginList = loginList;
        this.passwordList = passwordList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdminLoginTitle = new javax.swing.JLabel();
        lblAdminUsername = new javax.swing.JLabel();
        lblAdminPassword = new javax.swing.JLabel();
        txtAdminUsername = new javax.swing.JTextField();
        adminPasswordField = new javax.swing.JPasswordField();
        btnAdminLogin = new javax.swing.JButton();

        lblAdminLoginTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAdminLoginTitle.setText("Admin Login Page");

        lblAdminUsername.setText("Username");

        lblAdminPassword.setText("Password");

        txtAdminUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminUsernameActionPerformed(evt);
            }
        });

        btnAdminLogin.setText("Login");
        btnAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lblAdminLoginTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAdminPassword)
                            .addComponent(lblAdminUsername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAdminUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(adminPasswordField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnAdminLogin)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblAdminLoginTitle)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminUsername)
                    .addComponent(txtAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminPassword)
                    .addComponent(adminPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAdminLogin)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAdminUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminUsernameActionPerformed

    private void btnAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLoginActionPerformed

        // TODO add your handling code here:
        String inputUsername = txtAdminUsername.getText();
        char []inputCharPassword = adminPasswordField.getPassword();
        String inputPassword = new String(inputCharPassword);
        
        if (inputUsername.equals("admin") && inputPassword.equals("admin")) {
            AdminOperationsPanel adminPanel = new AdminOperationsPanel(personList,loginList, passwordList);
            frame = (MainJFrame)(JFrame)SwingUtilities.getWindowAncestor(this);
            frame.getSplitPane().setRightComponent(adminPanel);
            frame.setVisible(true);
            frame.revalidate(); 
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Admin Credentials");
        }

    }//GEN-LAST:event_btnAdminLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField adminPasswordField;
    private javax.swing.JButton btnAdminLogin;
    private javax.swing.JLabel lblAdminLoginTitle;
    private javax.swing.JLabel lblAdminPassword;
    private javax.swing.JLabel lblAdminUsername;
    private javax.swing.JTextField txtAdminUsername;
    // End of variables declaration//GEN-END:variables
}
