/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HashingPassword;
import model.LoginCredentials;
import model.LoginCredentialsList;
import model.Password;
import model.PasswordList;
import model.PersonDetailsList;

/**
 *
 * @author kamuni.saheeshna
 */
public class CreateUserPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateUserPanel
     */
    PersonDetailsList personList;
    LoginCredentialsList loginList;
    PasswordList passwordList;
 
    public CreateUserPanel(PersonDetailsList personList, LoginCredentialsList loginList,  PasswordList passwordList) {
        initComponents();
        this.personList = personList;
        this.loginList = loginList;  
        this.passwordList = passwordList;
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtNEUId = new javax.swing.JTextField();
        lblNEUId = new javax.swing.JLabel();
        btnCreateUser = new javax.swing.JButton();
        lblCreateUserTitle = new javax.swing.JLabel();

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        lblUsername.setText("Username:");

        lblPassword.setText("Password:");

        txtNEUId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNEUIdActionPerformed(evt);
            }
        });

        lblNEUId.setText("NEU ID:");

        btnCreateUser.setText("Create User");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });

        lblCreateUserTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCreateUserTitle.setText("Create User");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblNEUId)
                        .addComponent(lblUsername)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(txtNEUId))
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnCreateUser))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(lblCreateUserTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblCreateUserTitle)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNEUId)
                    .addComponent(txtNEUId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword))
                .addGap(18, 18, 18)
                .addComponent(btnCreateUser)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtNEUIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNEUIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNEUIdActionPerformed

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        // TODO add your handling code here:
        int createUserRowCount = -1;
        LoginCredentials signUp = loginList.addCredentials();
        Password createUserPassword = passwordList.newPasswordList();
        
        String inputNEUId = txtNEUId.getText();       
        AdminOperationsPanel peoplePanel = new AdminOperationsPanel(personList, loginList, passwordList);
        DefaultTableModel model = peoplePanel.getTable();
        
        for (int i = 0; i < model.getRowCount(); i++) {
            String neuId = model.getValueAt(i, 0).toString();
            if (neuId.equals(inputNEUId)) {
                createUserRowCount = i;
                signUp.setUserName(txtUsername.getText());
                char[] inputPasswordChars = txtPassword.getPassword();
                String inputPassword = new String(inputPasswordChars);
                createUserPassword.setPassword(inputPassword);
                String hashedPassword = HashingPassword.hashPassword(inputPassword); 
                createUserPassword.setHashPassword(hashedPassword);
                signUp.setEnabled("True");
                JOptionPane.showMessageDialog(this, "User Created");
            }
        }
        if (createUserRowCount == -1) {
            JOptionPane.showMessageDialog(this, "NEU ID not found.");
        }     
    }//GEN-LAST:event_btnCreateUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JLabel lblCreateUserTitle;
    private javax.swing.JLabel lblNEUId;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtNEUId;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
