/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.LoginCredentialsList;
import model.PersonDetails;
import model.PersonDetailsList;

/**
 *
 * @author kamuni.saheeshna
 */
public class ListPeoplePanel extends javax.swing.JPanel {

    /**
     * Creates new form ListPeoplePanel
     */
    PersonDetailsList personList;
   
    public ListPeoplePanel(PersonDetailsList personList, LoginCredentialsList loginList) {
        initComponents();
        this.personList=personList;
        peoplePopulate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblListPeopleTitle = new javax.swing.JLabel();
        listPeopleScrollPane = new javax.swing.JScrollPane();
        tblListPeople = new javax.swing.JTable();
        lblNEUIdA = new javax.swing.JLabel();
        lblFirstNameA = new javax.swing.JLabel();
        lblLastNameA = new javax.swing.JLabel();
        lblGenderA = new javax.swing.JLabel();
        lblDateOfBirthA = new javax.swing.JLabel();
        txtNEUIdA = new javax.swing.JTextField();
        txtFirstNameA = new javax.swing.JTextField();
        txtLastNameA = new javax.swing.JTextField();
        txtGenderA = new javax.swing.JTextField();
        txtDateOfBirthA = new javax.swing.JTextField();
        btnSearchA = new javax.swing.JButton();
        txtSearchA = new javax.swing.JTextField();
        lblSearchA = new javax.swing.JLabel();

        lblListPeopleTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblListPeopleTitle.setText("List People");

        tblListPeople.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NEU Id", "First Name", "Last Name", "Gender", "Date Of Birth"
            }
        ));
        listPeopleScrollPane.setViewportView(tblListPeople);

        lblNEUIdA.setText("NEU ID:");

        lblFirstNameA.setText("First Name:");

        lblLastNameA.setText("Last Name:");

        lblGenderA.setText("Gender:");

        lblDateOfBirthA.setText("Date Of Birth:");

        txtNEUIdA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNEUIdAActionPerformed(evt);
            }
        });

        txtGenderA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderAActionPerformed(evt);
            }
        });

        txtDateOfBirthA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateOfBirthAActionPerformed(evt);
            }
        });

        btnSearchA.setText("Search");
        btnSearchA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAActionPerformed(evt);
            }
        });

        lblSearchA.setText("Search:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(listPeopleScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLastNameA)
                            .addComponent(lblFirstNameA)
                            .addComponent(lblGenderA)
                            .addComponent(lblDateOfBirthA)
                            .addComponent(lblNEUIdA))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNEUIdA, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(txtFirstNameA)
                            .addComponent(txtLastNameA)
                            .addComponent(txtGenderA)
                            .addComponent(txtDateOfBirthA))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblSearchA)
                .addGap(44, 44, 44)
                .addComponent(txtSearchA, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnSearchA, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(lblListPeopleTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblListPeopleTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblSearchA))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearchA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearchA)))
                .addGap(18, 18, 18)
                .addComponent(listPeopleScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNEUIdA)
                    .addComponent(txtNEUIdA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstNameA)
                    .addComponent(txtFirstNameA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastNameA)
                    .addComponent(txtLastNameA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenderA)
                    .addComponent(txtGenderA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateOfBirthA)
                    .addComponent(txtDateOfBirthA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNEUIdAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNEUIdAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNEUIdAActionPerformed

    private void txtGenderAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderAActionPerformed

    private void txtDateOfBirthAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateOfBirthAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateOfBirthAActionPerformed

    private void btnSearchAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAActionPerformed
        // TODO add your handling code here:
        int listPeopleRowCount = -1;
        String inputNEUId = txtSearchA.getText();
        DefaultTableModel model = (DefaultTableModel) tblListPeople.getModel();
        
        for (int i = 0; i < model.getRowCount(); i++) {
            String neuId = model.getValueAt(i, 0).toString();
            if (neuId.equals(inputNEUId)) {
                listPeopleRowCount = i;
                break;
            }
        }
        if (listPeopleRowCount == -1) {
            JOptionPane.showMessageDialog(this, "NEU ID not found.");
            return;
        }

        PersonDetails selectedNEUID = (PersonDetails) model.getValueAt(listPeopleRowCount, 0);
        txtNEUIdA.setText(String.valueOf(selectedNEUID.getNeuID()));
        txtFirstNameA.setText(selectedNEUID.getFirstName());
        txtLastNameA.setText(selectedNEUID.getLastName());
        txtGenderA.setText(selectedNEUID.getGender());
        txtDateOfBirthA.setText(selectedNEUID.getDateOfBirth());
    }//GEN-LAST:event_btnSearchAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchA;
    private javax.swing.JLabel lblDateOfBirthA;
    private javax.swing.JLabel lblFirstNameA;
    private javax.swing.JLabel lblGenderA;
    private javax.swing.JLabel lblLastNameA;
    private javax.swing.JLabel lblListPeopleTitle;
    private javax.swing.JLabel lblNEUIdA;
    private javax.swing.JLabel lblSearchA;
    private javax.swing.JScrollPane listPeopleScrollPane;
    private javax.swing.JTable tblListPeople;
    private javax.swing.JTextField txtDateOfBirthA;
    private javax.swing.JTextField txtFirstNameA;
    private javax.swing.JTextField txtGenderA;
    private javax.swing.JTextField txtLastNameA;
    private javax.swing.JTextField txtNEUIdA;
    private javax.swing.JTextField txtSearchA;
    // End of variables declaration//GEN-END:variables
    
    private void peoplePopulate() {
        DefaultTableModel model = (DefaultTableModel) tblListPeople.getModel();
        model.setRowCount(0);
   
        for (int i = 0; i < personList.getPersonList().size(); i++) {
            PersonDetails p = personList.getPersonList().get(i);
            Object row[] = new Object[5];
            row[0]= p;
            row[1]= p.getFirstName();
            row[2]= p.getLastName();
            row[3] =p.getGender();
            row[4] =p.getDateOfBirth();
            
            model.addRow(row);
        }
    }
    
    public DefaultTableModel getPeopleTable(){
        DefaultTableModel peopleTable = (DefaultTableModel) tblListPeople.getModel();
        return peopleTable;
    }
}
