/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JSplitPane;
import model.LoginCredentialsList;
import model.PasswordList;
import model.PersonDetailsList;

/**
 *
 * @author kamuni.saheeshna
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    LoginCredentialsList loginCredentialsList;
    PersonDetailsList personList;
    PasswordList passwordList;
    public MainJFrame() {
        initComponents();
        personList = new PersonDetailsList();
        loginCredentialsList = new LoginCredentialsList();
        passwordList = new PasswordList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginSplitPane = new javax.swing.JSplitPane();
        loginControlArea = new javax.swing.JPanel();
        btnAdminLogin = new javax.swing.JButton();
        btnUserLogin = new javax.swing.JButton();
        loginWorkArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdminLogin.setText("Admin Login");
        btnAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLoginActionPerformed(evt);
            }
        });

        btnUserLogin.setText("User Login");
        btnUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginControlAreaLayout = new javax.swing.GroupLayout(loginControlArea);
        loginControlArea.setLayout(loginControlAreaLayout);
        loginControlAreaLayout.setHorizontalGroup(
            loginControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginControlAreaLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(btnUserLogin)
                .addContainerGap())
            .addGroup(loginControlAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdminLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loginControlAreaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdminLogin, btnUserLogin});

        loginControlAreaLayout.setVerticalGroup(
            loginControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginControlAreaLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(btnAdminLogin)
                .addGap(64, 64, 64)
                .addComponent(btnUserLogin)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        loginControlAreaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdminLogin, btnUserLogin});

        loginSplitPane.setLeftComponent(loginControlArea);

        javax.swing.GroupLayout loginWorkAreaLayout = new javax.swing.GroupLayout(loginWorkArea);
        loginWorkArea.setLayout(loginWorkAreaLayout);
        loginWorkAreaLayout.setHorizontalGroup(
            loginWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );
        loginWorkAreaLayout.setVerticalGroup(
            loginWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );

        loginSplitPane.setRightComponent(loginWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginSplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLoginActionPerformed
        // TODO add your handling code here:
        AdminLogin adminLoginPanel = new AdminLogin(personList, loginCredentialsList, passwordList);
        loginSplitPane.setRightComponent(adminLoginPanel);
    }//GEN-LAST:event_btnAdminLoginActionPerformed

    private void btnUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserLoginActionPerformed
        // TODO add your handling code here:
        UserLogin userLoginPanel = new UserLogin(personList, loginCredentialsList, passwordList);
        loginSplitPane.setRightComponent(userLoginPanel);
    }//GEN-LAST:event_btnUserLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminLogin;
    private javax.swing.JButton btnUserLogin;
    private javax.swing.JPanel loginControlArea;
    private javax.swing.JSplitPane loginSplitPane;
    private javax.swing.JPanel loginWorkArea;
    // End of variables declaration//GEN-END:variables

    public JSplitPane getSplitPane() {
        return loginSplitPane;
   }

}
