/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.LoginCredentials;
import model.LoginCredentialsList;
import model.Password;
import model.PasswordList;
import model.PersonDetails;
import model.PersonDetailsList;

/**
 *
 * @author kamuni.saheeshna
 */
public class UserLogin extends javax.swing.JPanel {

    /**
     * Creates new form UserLogin
     */
    PersonDetailsList personList;
    LoginCredentialsList loginCredentialsList;
    MainJFrame frame;
    PasswordList passwordList;

    public UserLogin(PersonDetailsList personList, LoginCredentialsList loginCredentialsList,PasswordList passwordList ) {
        initComponents();
        this.loginCredentialsList=loginCredentialsList;
        this.personList = personList; 
        this.passwordList = passwordList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserLoginTitle = new javax.swing.JLabel();
        lblUserUsername = new javax.swing.JLabel();
        lblUserPassword = new javax.swing.JLabel();
        txtUserUsername = new javax.swing.JTextField();
        userPasswordField = new javax.swing.JPasswordField();
        btnUserLogin = new javax.swing.JButton();

        lblUserLoginTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserLoginTitle.setText("User Login Page");

        lblUserUsername.setText("Username");

        lblUserPassword.setText("Password");

        txtUserUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserUsernameActionPerformed(evt);
            }
        });

        userPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPasswordFieldActionPerformed(evt);
            }
        });

        btnUserLogin.setText("Login");
        btnUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lblUserLoginTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUserPassword)
                            .addComponent(lblUserUsername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUserUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(userPasswordField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnUserLogin)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblUserLoginTitle)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserUsername)
                    .addComponent(txtUserUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserPassword)
                    .addComponent(userPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUserLogin)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserUsernameActionPerformed

    private void btnUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserLoginActionPerformed
// TODO add your handling code here:
        AdminOperationsPanel admin = new AdminOperationsPanel(personList, loginCredentialsList, passwordList);
        DefaultTableModel model= admin.getTable();
        String enteredUsername = txtUserUsername.getText();
        char[] enteredPasswordChars = userPasswordField.getPassword();
        String enteredPassword = new String(enteredPasswordChars);
        
        if(model.getRowCount()==0)
            JOptionPane.showMessageDialog(this, "User Not Registered.");
    
        for (int i = 0; i < model.getRowCount(); i++) {
            LoginCredentials sign = (LoginCredentials) model.getValueAt(i, 3);
            Password pass = (Password) model.getValueAt(i, 4);
            String username = sign.getUserName();
            String password = pass.getPassword();
            if(enteredUsername.equals(username) && (enteredPassword.equals(password))){
              UserOperationsPanel userOperationsPanel = new UserOperationsPanel(personList, loginCredentialsList, passwordList);
              PersonDetails person = (PersonDetails) model.getValueAt(i, 0);
              LoginCredentials signUp = (LoginCredentials) model.getValueAt(i, 3);
              
              userOperationsPanel.settxtNEUID(String.valueOf(person.getNeuID()));
              userOperationsPanel.settxtFirstName(person.getFirstName());
              userOperationsPanel.settxtLastName(person.getLastName());
              userOperationsPanel.settxtGender(person.getGender());
              userOperationsPanel.settxtDOB(person.getDateOfBirth());
              userOperationsPanel.settxtUsername(signUp.getUserName());
              
              frame = (MainJFrame)(JFrame)SwingUtilities.getWindowAncestor(this);
              frame.getSplitPane().setRightComponent(userOperationsPanel);
              frame.setVisible(true);
              frame.revalidate();
            } else if(enteredUsername.equals(username) && (!enteredPassword.equals(password) )) {
                JOptionPane.showMessageDialog(this, "Wrong Password");
            } else if(!enteredUsername.equals(username) && (!enteredPassword.equals(password) )) {
                JOptionPane.showMessageDialog(this, "User Not Registered");
            } 
        }  
    }//GEN-LAST:event_btnUserLoginActionPerformed

    private void userPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPasswordFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUserLogin;
    private javax.swing.JLabel lblUserLoginTitle;
    private javax.swing.JLabel lblUserPassword;
    private javax.swing.JLabel lblUserUsername;
    private javax.swing.JTextField txtUserUsername;
    private javax.swing.JPasswordField userPasswordField;
    // End of variables declaration//GEN-END:variables
    
    
}
