/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.RoleSelection.Admin;

import Business.Course.Course;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.Course.CourseList;
import Business.Degree.DegreeList;
import Business.Professor.ProfessorList;
import Business.ProfessorLogin.ProfessorLoginList;
import Business.Student.StudentList;
import Business.StudentLogin.StudentLoginList;
import Business.ThirdParty.ThirdPartyList;
import UserInterface.RoleSelection.MainJFrame;
import java.util.HashMap;
import java.util.List;

/**
 *
 * @author metla
 */
public class AdminViewPanel extends javax.swing.JPanel {
    /**
     * Creates new form AdminViewPanel
     */
    MainJFrame frame;
    ProfessorList professorList;
    ProfessorLoginList professorLoginList;
    CourseList courseList;
    StudentList studentList;
    StudentLoginList studentLoginList;
    ThirdPartyList thirdPartyList;
    JPanel userProcessContainer;
    DegreeList degreeList;
    HashMap<String, List<Course>> studentCour;
    
    public AdminViewPanel(JPanel userProcessContainer, ProfessorList professorList, ProfessorLoginList professorLoginList, CourseList courseList, StudentList studentList, StudentLoginList studentLoginList, ThirdPartyList thirdPartyList, HashMap<String, List<Course>> studentCour, DegreeList degreeList) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.professorList = professorList;
        this.professorLoginList = professorLoginList;
        this.courseList =  courseList;
        this.studentList = studentList;
        this.studentLoginList = studentLoginList;
        this.thirdPartyList = thirdPartyList;
        this.studentCour = studentCour;
        this.degreeList = degreeList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdminView = new javax.swing.JLabel();
        lblChoose = new javax.swing.JLabel();
        btnProfessorCatalog = new javax.swing.JButton();
        btnCourseCatalog = new javax.swing.JButton();
        btnStudentCatalog = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnDegreeCatalog = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 153));

        lblAdminView.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAdminView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdminView.setText("ADMIN VIEW");

        lblChoose.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblChoose.setText("Choose one of the controls below:");

        btnProfessorCatalog.setBackground(new java.awt.Color(204, 204, 255));
        btnProfessorCatalog.setText("Professor Catalog");
        btnProfessorCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfessorCatalogActionPerformed(evt);
            }
        });

        btnCourseCatalog.setBackground(new java.awt.Color(204, 204, 255));
        btnCourseCatalog.setText("Course Catalog");
        btnCourseCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseCatalogActionPerformed(evt);
            }
        });

        btnStudentCatalog.setBackground(new java.awt.Color(204, 204, 255));
        btnStudentCatalog.setText("Student Catalog");
        btnStudentCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentCatalogActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(204, 204, 255));
        btnBack.setText("Admin Logout");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDegreeCatalog.setBackground(new java.awt.Color(204, 204, 255));
        btnDegreeCatalog.setText(" Degree");
        btnDegreeCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDegreeCatalogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAdminView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnProfessorCatalog)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnStudentCatalog))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCourseCatalog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDegreeCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(8, 8, 8)))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCourseCatalog, btnProfessorCatalog, btnStudentCatalog});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminView)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addComponent(lblChoose)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProfessorCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStudentCatalog))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCourseCatalog)
                    .addComponent(btnDegreeCatalog))
                .addContainerGap(269, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCourseCatalog, btnDegreeCatalog, btnProfessorCatalog, btnStudentCatalog});

    }// </editor-fold>//GEN-END:initComponents

    private void btnProfessorCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfessorCatalogActionPerformed
        // TODO add your handling code here:
        ProfessorCatalogPanel professorcatalog = new ProfessorCatalogPanel(userProcessContainer,professorList, professorLoginList, courseList, studentList, studentLoginList, thirdPartyList, studentCour, degreeList);          
        userProcessContainer.add("ProfessorCatalog", professorcatalog);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
  
    }//GEN-LAST:event_btnProfessorCatalogActionPerformed

    private void btnStudentCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentCatalogActionPerformed
        // TODO add your handling code here:
        StudentCatalogPanel studentcatalog = new StudentCatalogPanel(userProcessContainer, professorList, professorLoginList,courseList, studentList, studentLoginList, thirdPartyList,studentCour, degreeList);          
        userProcessContainer.add("StudentCatalog", studentcatalog);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
    }//GEN-LAST:event_btnStudentCatalogActionPerformed

    private void btnCourseCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseCatalogActionPerformed
        // TODO add your handling code here:
        CourseCatalogPanel coursecatalog = new CourseCatalogPanel(userProcessContainer, professorList, professorLoginList, courseList, studentList, studentLoginList, thirdPartyList,studentCour, degreeList);          
        userProcessContainer.add("CourseCatalog", coursecatalog);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
  
    }//GEN-LAST:event_btnCourseCatalogActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDegreeCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDegreeCatalogActionPerformed
        // TODO add your handling code here:
        DegreeCatalogPanel degree = new DegreeCatalogPanel(userProcessContainer, professorList, professorLoginList, courseList, studentList, studentLoginList, thirdPartyList, studentCour, degreeList);               
        userProcessContainer.add("DegreePanel", degree);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDegreeCatalogActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCourseCatalog;
    private javax.swing.JButton btnDegreeCatalog;
    private javax.swing.JButton btnProfessorCatalog;
    private javax.swing.JButton btnStudentCatalog;
    private javax.swing.JLabel lblAdminView;
    private javax.swing.JLabel lblChoose;
    // End of variables declaration//GEN-END:variables
}
