/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;

import Business.Course.CourseList;
import Business.Degree;
import Business.DegreeList;
import Business.ProfessorList;
import Business.ProfessorLoginList;
import Business.StudentList;
import Business.StudentLoginList;
import Business.ThirdPartyList;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author metla
 */
public class DegreePanel extends javax.swing.JPanel {
    ProfessorList professorList;
    ProfessorLoginList professorLoginList;
    CourseList courseList;
    MainJFrame frame;
    StudentList studentList;
    StudentLoginList studentLoginList;
    ThirdPartyList thirdPartyList;
    DegreeList degreeList;
    JPanel userProcessContainer;


    /**
     * Creates new form DegreePanel
     * @param userProcessContainer
     * @param degreeList
     * @param professorLoginList
     */
    public DegreePanel(JPanel userProcessContainer, ProfessorList professorList, ProfessorLoginList professorLoginList, CourseList courseList, StudentList studentList, StudentLoginList studentLoginList, ThirdPartyList thirdPartyList, DegreeList degreeList) {
        initComponents();
        this.professorList = professorList;
        this.professorLoginList = professorLoginList;
        this.courseList = courseList;
        this.studentList = studentList;
        this.studentLoginList = studentLoginList;
        this.userProcessContainer= userProcessContainer;
        this.thirdPartyList = thirdPartyList;
        this.degreeList = degreeList;
        populateDegreeTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDegree = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDegree = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblDegreeName = new javax.swing.JLabel();
        lblRequiredCredits = new javax.swing.JLabel();
        lblRequiredGPA = new javax.swing.JLabel();
        txtDegreeName = new javax.swing.JTextField();
        txtRequiredCredits = new javax.swing.JTextField();
        txtRequiredGPA = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        lblDegree.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDegree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDegree.setText("DEGREE");

        tblDegree.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Degree Name", "Required Credits", "Required GPA"
            }
        ));
        jScrollPane1.setViewportView(tblDegree);

        btnAdd.setText("ADD DEGREE");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("UPDATE DEGREE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE DEGREE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblDegreeName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDegreeName.setText("Degree Name");

        lblRequiredCredits.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRequiredCredits.setText("Required Credits");

        lblRequiredGPA.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRequiredGPA.setText("Required GPA");

        txtRequiredCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRequiredCreditsActionPerformed(evt);
            }
        });

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDegree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRequiredCredits)
                                    .addComponent(lblRequiredGPA)
                                    .addComponent(lblDegreeName))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRequiredCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRequiredGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDegreeName, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(278, 278, 278)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAdd)
                                    .addComponent(btnDelete)
                                    .addComponent(btnUpdate)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack))
                        .addGap(38, 38, 38))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdd, btnDelete, btnUpdate});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDegreeName, txtRequiredCredits, txtRequiredGPA});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDegree)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblDegreeName)
                        .addGap(31, 31, 31)
                        .addComponent(lblRequiredCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(lblRequiredGPA))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnUpdate)
                        .addGap(31, 31, 31)
                        .addComponent(btnDelete))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtDegreeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(txtRequiredCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txtRequiredGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdd, btnDelete, btnUpdate});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtDegreeName, txtRequiredCredits, txtRequiredGPA});

    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String degreeName = txtDegreeName.getText();
        String requiredCredits = txtRequiredCredits.getText();
        String requiredGPA = txtRequiredGPA.getText();
        Degree d= degreeList.addNewDegree();
        d.setDegreeName(degreeName);
        d.setRequiredCredits(requiredCredits);
        d.setRequiredGPA(requiredGPA);
        populateDegreeTable();

        JOptionPane.showMessageDialog(this, "Degrees added");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String degreeName = txtDegreeName.getText();
        String requiredCredits = txtRequiredCredits.getText();
        String requiredGPA = txtRequiredGPA.getText();
        DefaultTableModel model= (DefaultTableModel) tblDegree.getModel();
        int selectedRowIndex = tblDegree.getSelectedRow();
        Degree selectedDegree = (Degree) model.getValueAt(selectedRowIndex, 0);
        selectedDegree.setDegreeName(degreeName);
        selectedDegree.setRequiredCredits(requiredCredits);
        selectedDegree.setRequiredGPA(requiredGPA);
        populateDegreeTable();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblDegree.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblDegree.getModel();
        Degree selectedDegree = (Degree) model.getValueAt(selectedRowIndex, 0);
        degreeList.deleteDegree(selectedDegree);
        JOptionPane.showMessageDialog(this, "Degree deleted.");
        populateDegreeTable();
    }//GEN-LAST:event_btnDeleteActionPerformed
    private void populateDegreeTable() {
    DefaultTableModel model = (DefaultTableModel) tblDegree.getModel();
    model.setRowCount(0);
    JOptionPane.showMessageDialog(this,degreeList.getDegreeList().size() );
    for (int i = 0; i < degreeList.getDegreeList().size(); i++){
        //Person person1 = personList.getPersonList().get(i);
        Degree d = degreeList.getDegreeList().get(i);
        
        Object[] row = new Object[3];
        row[0] = d; // Assuming getProfId is a method
        row[1] = d.getRequiredCredits();
        row[2] = d.getRequiredGPA();
        model.addRow(row);
    }
}
    private void txtRequiredCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRequiredCreditsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRequiredCreditsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDegree;
    private javax.swing.JLabel lblDegreeName;
    private javax.swing.JLabel lblRequiredCredits;
    private javax.swing.JLabel lblRequiredGPA;
    private javax.swing.JTable tblDegree;
    private javax.swing.JTextField txtDegreeName;
    private javax.swing.JTextField txtRequiredCredits;
    private javax.swing.JTextField txtRequiredGPA;
    // End of variables declaration//GEN-END:variables
}
