/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.Address;
import model.Doctor;
import model.Driver;
import model.InsuranceCoverage;
import model.Patient;
import model.Person;
import model.VehicleRegistration;

/**
 *
 * @author kamuni.saheeshna
 */
public class DisplayReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayReportJPanel
     */
    Person person;
    Address address;
    Driver driver;
    VehicleRegistration vehicleRegistration;
    Patient patient;
    Doctor doctor;
    InsuranceCoverage insuranceCoverage;
    
    public DisplayReportJPanel(Person p, Address address, Driver driver, 
            VehicleRegistration vehicleRegistration, Patient patient, Doctor doctor, InsuranceCoverage insuranceCoverage) {
        initComponents();
        this.person = p;
        this.address = address;
        this.driver = driver;
        this.vehicleRegistration = vehicleRegistration;
        this.patient = patient;
        this.doctor = doctor;
        this.insuranceCoverage = insuranceCoverage; 
        displayPerson();
        displayAddress();
        displayDriver();
        displayVehicleRegistration();
        displayPatient();
        displayDoctor();
        displayInsuranceCoverage();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportScrollPane = new javax.swing.JScrollPane();
        reportPanel = new javax.swing.JPanel();
        lblDoctorGender = new javax.swing.JLabel();
        txtDateOfExpiration = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        lblCorporateID = new javax.swing.JLabel();
        txtDeductible = new javax.swing.JTextField();
        lblManufacturer = new javax.swing.JLabel();
        txtCorporateID = new javax.swing.JTextField();
        txtWebsiteURL = new javax.swing.JTextField();
        txtOccupation = new javax.swing.JTextField();
        lblAllergies = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        txtDoctorName = new javax.swing.JTextField();
        lblWebsiteURL = new javax.swing.JLabel();
        txtIssuingState = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        txtDriverLicenseNumber = new javax.swing.JTextField();
        txtDateOfBirth = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtEmailID = new javax.swing.JTextField();
        txtDoctorID = new javax.swing.JTextField();
        lblOnMedication = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        txtPictureURL = new javax.swing.JTextField();
        lblAddress2 = new javax.swing.JLabel();
        lblDateOfExpiration = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        txtDoctorEmailID = new javax.swing.JTextField();
        lblPremium = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        benefitsDescScrollPane = new javax.swing.JScrollPane();
        txtAreaBenefitsDesc = new javax.swing.JTextArea();
        txtPinCode = new javax.swing.JTextField();
        formattedDateOfLastVisit = new javax.swing.JFormattedTextField();
        lblPictureURL = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblPinCode = new javax.swing.JLabel();
        lblPhoneNumber1 = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        lblDoctorName = new javax.swing.JLabel();
        lblInsuranceCompany = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        lblDateOfLastVisit = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtdriverLicenseNumber = new javax.swing.JLabel();
        txtMedicalSchool = new javax.swing.JTextField();
        txtVehicleModel = new javax.swing.JTextField();
        lblPrimaryDoctor = new javax.swing.JLabel();
        txtOfficePhoneNumber = new javax.swing.JTextField();
        lblVehicleModel = new javax.swing.JLabel();
        txtPrimaryDoctor = new javax.swing.JTextField();
        lblPatientID = new javax.swing.JLabel();
        txtDoctorGender = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        lblOccupation = new javax.swing.JLabel();
        lblCompanyAddress = new javax.swing.JLabel();
        lblIssuingState = new javax.swing.JLabel();
        lblDeductible = new javax.swing.JLabel();
        lblDateOfBirth = new javax.swing.JLabel();
        txtOwnerName = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        lblDoctorEmailID = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblEmailID = new javax.swing.JLabel();
        lblOwnerName = new javax.swing.JLabel();
        txtOfficeAddress = new javax.swing.JTextField();
        txtAddress1 = new javax.swing.JTextField();
        txtManufacturer = new javax.swing.JTextField();
        lblOfficeAddress = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        txtAddress2 = new javax.swing.JTextField();
        lblSpecialty = new javax.swing.JLabel();
        txtInsuranceCompany = new javax.swing.JTextField();
        txtPremium = new javax.swing.JTextField();
        lblAddress1 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtCompanyAddress = new javax.swing.JTextField();
        txtSpecialty = new javax.swing.JTextField();
        lblMedicalSchool = new javax.swing.JLabel();
        lblBenefitsDesc = new javax.swing.JLabel();
        lblDoctorID = new javax.swing.JLabel();
        txtAllergies = new javax.swing.JTextField();
        txtOnMedication = new javax.swing.JTextField();
        lblPatientReportTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        reportPanel.setBackground(new java.awt.Color(255, 255, 51));
        reportPanel.setFocusTraversalPolicyProvider(true);

        lblDoctorGender.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblDoctorGender.setForeground(new java.awt.Color(0, 153, 255));
        lblDoctorGender.setText("Gender");

        txtDateOfExpiration.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtDateOfExpiration.setForeground(new java.awt.Color(0, 153, 255));
        txtDateOfExpiration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateOfExpirationActionPerformed(evt);
            }
        });

        lblLastName.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(0, 153, 255));
        lblLastName.setText("Last Name");

        lblCorporateID.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblCorporateID.setForeground(new java.awt.Color(0, 153, 255));
        lblCorporateID.setText("Corporate ID");

        txtDeductible.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtDeductible.setForeground(new java.awt.Color(0, 153, 255));

        lblManufacturer.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblManufacturer.setForeground(new java.awt.Color(0, 153, 255));
        lblManufacturer.setText("Manufacturer");

        txtCorporateID.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtCorporateID.setForeground(new java.awt.Color(0, 153, 255));
        txtCorporateID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorporateIDActionPerformed(evt);
            }
        });

        txtWebsiteURL.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtWebsiteURL.setForeground(new java.awt.Color(0, 153, 255));

        txtOccupation.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtOccupation.setForeground(new java.awt.Color(0, 153, 255));

        lblAllergies.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblAllergies.setForeground(new java.awt.Color(0, 153, 255));
        lblAllergies.setText("Allergies");

        txtPatientName.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtPatientName.setForeground(new java.awt.Color(0, 153, 255));
        txtPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientNameActionPerformed(evt);
            }
        });

        txtDoctorName.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtDoctorName.setForeground(new java.awt.Color(0, 153, 255));

        lblWebsiteURL.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblWebsiteURL.setForeground(new java.awt.Color(0, 153, 255));
        lblWebsiteURL.setText("Website URL");

        txtIssuingState.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtIssuingState.setForeground(new java.awt.Color(0, 153, 255));
        txtIssuingState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIssuingStateActionPerformed(evt);
            }
        });

        lblSSN.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblSSN.setForeground(new java.awt.Color(0, 153, 255));
        lblSSN.setText("Social Security Number");

        txtDriverLicenseNumber.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtDriverLicenseNumber.setForeground(new java.awt.Color(0, 153, 255));

        txtDateOfBirth.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtDateOfBirth.setForeground(new java.awt.Color(0, 153, 255));

        txtPhoneNumber.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtPhoneNumber.setForeground(new java.awt.Color(0, 153, 255));
        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });

        txtEmailID.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtEmailID.setForeground(new java.awt.Color(0, 153, 255));

        txtDoctorID.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtDoctorID.setForeground(new java.awt.Color(0, 153, 255));
        txtDoctorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorIDActionPerformed(evt);
            }
        });

        lblOnMedication.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblOnMedication.setForeground(new java.awt.Color(0, 153, 255));
        lblOnMedication.setText("On Medication");

        lblCountry.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblCountry.setForeground(new java.awt.Color(0, 153, 255));
        lblCountry.setText("Country");

        txtPictureURL.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtPictureURL.setForeground(new java.awt.Color(0, 153, 255));
        txtPictureURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPictureURLActionPerformed(evt);
            }
        });

        lblAddress2.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblAddress2.setForeground(new java.awt.Color(0, 153, 255));
        lblAddress2.setText("Address 2");

        lblDateOfExpiration.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblDateOfExpiration.setForeground(new java.awt.Color(0, 153, 255));
        lblDateOfExpiration.setText("Date Of Expiration");

        txtSSN.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtSSN.setForeground(new java.awt.Color(0, 153, 255));
        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });

        txtDoctorEmailID.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtDoctorEmailID.setForeground(new java.awt.Color(0, 153, 255));

        lblPremium.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblPremium.setForeground(new java.awt.Color(0, 153, 255));
        lblPremium.setText("Premium Amount ($)");

        lblState.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblState.setForeground(new java.awt.Color(0, 153, 255));
        lblState.setText("State");

        txtAreaBenefitsDesc.setColumns(20);
        txtAreaBenefitsDesc.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtAreaBenefitsDesc.setForeground(new java.awt.Color(0, 153, 255));
        txtAreaBenefitsDesc.setRows(5);
        benefitsDescScrollPane.setViewportView(txtAreaBenefitsDesc);

        txtPinCode.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtPinCode.setForeground(new java.awt.Color(0, 153, 255));
        txtPinCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPinCodeActionPerformed(evt);
            }
        });

        formattedDateOfLastVisit.setForeground(new java.awt.Color(0, 153, 255));
        formattedDateOfLastVisit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formattedDateOfLastVisitActionPerformed(evt);
            }
        });

        lblPictureURL.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblPictureURL.setForeground(new java.awt.Color(0, 153, 255));
        lblPictureURL.setText("Pricture URL");

        lblPhoneNumber.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(0, 153, 255));
        lblPhoneNumber.setText("Phone Number");

        txtFirstName.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtFirstName.setForeground(new java.awt.Color(0, 153, 255));

        lblPinCode.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblPinCode.setForeground(new java.awt.Color(0, 153, 255));
        lblPinCode.setText("Pin Code");

        lblPhoneNumber1.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblPhoneNumber1.setForeground(new java.awt.Color(0, 153, 255));
        lblPhoneNumber1.setText("Office Phone Number");

        lblPatientName.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblPatientName.setForeground(new java.awt.Color(0, 153, 255));
        lblPatientName.setText("Patient Name");

        lblDoctorName.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblDoctorName.setForeground(new java.awt.Color(0, 153, 255));
        lblDoctorName.setText("Doctor Name");

        lblInsuranceCompany.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblInsuranceCompany.setForeground(new java.awt.Color(0, 153, 255));
        lblInsuranceCompany.setText("Insurance Company");

        txtPatientID.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtPatientID.setForeground(new java.awt.Color(0, 153, 255));
        txtPatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientIDActionPerformed(evt);
            }
        });

        lblDateOfLastVisit.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblDateOfLastVisit.setForeground(new java.awt.Color(0, 153, 255));
        lblDateOfLastVisit.setText("Date Of Last Visit");

        txtGender.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtGender.setForeground(new java.awt.Color(0, 153, 255));

        lblCity.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblCity.setForeground(new java.awt.Color(0, 153, 255));
        lblCity.setText("City");

        txtdriverLicenseNumber.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtdriverLicenseNumber.setForeground(new java.awt.Color(0, 153, 255));
        txtdriverLicenseNumber.setText("Driver License Number");

        txtMedicalSchool.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtMedicalSchool.setForeground(new java.awt.Color(0, 153, 255));

        txtVehicleModel.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtVehicleModel.setForeground(new java.awt.Color(0, 153, 255));
        txtVehicleModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleModelActionPerformed(evt);
            }
        });

        lblPrimaryDoctor.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblPrimaryDoctor.setForeground(new java.awt.Color(0, 153, 255));
        lblPrimaryDoctor.setText("Primary Doctor");

        txtOfficePhoneNumber.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtOfficePhoneNumber.setForeground(new java.awt.Color(0, 153, 255));
        txtOfficePhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOfficePhoneNumberActionPerformed(evt);
            }
        });

        lblVehicleModel.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblVehicleModel.setForeground(new java.awt.Color(0, 153, 255));
        lblVehicleModel.setText("Vehicle Model");

        txtPrimaryDoctor.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtPrimaryDoctor.setForeground(new java.awt.Color(0, 153, 255));

        lblPatientID.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblPatientID.setForeground(new java.awt.Color(0, 153, 255));
        lblPatientID.setText("Patient ID");

        txtDoctorGender.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtDoctorGender.setForeground(new java.awt.Color(0, 153, 255));

        txtCountry.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtCountry.setForeground(new java.awt.Color(0, 153, 255));
        txtCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountryActionPerformed(evt);
            }
        });

        lblOccupation.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblOccupation.setForeground(new java.awt.Color(0, 153, 255));
        lblOccupation.setText("Occupation");

        lblCompanyAddress.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblCompanyAddress.setForeground(new java.awt.Color(0, 153, 255));
        lblCompanyAddress.setText("Company Address");

        lblIssuingState.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblIssuingState.setForeground(new java.awt.Color(0, 153, 255));
        lblIssuingState.setText("Issuing State");

        lblDeductible.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblDeductible.setForeground(new java.awt.Color(0, 153, 255));
        lblDeductible.setText("Deductible Amount ($)");

        lblDateOfBirth.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblDateOfBirth.setForeground(new java.awt.Color(0, 153, 255));
        lblDateOfBirth.setText("Date Of Birth");

        txtOwnerName.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtOwnerName.setForeground(new java.awt.Color(0, 153, 255));

        txtState.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtState.setForeground(new java.awt.Color(0, 153, 255));
        txtState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateActionPerformed(evt);
            }
        });

        lblGender.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblGender.setForeground(new java.awt.Color(0, 153, 255));
        lblGender.setText("Gender");

        lblDoctorEmailID.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblDoctorEmailID.setForeground(new java.awt.Color(0, 153, 255));
        lblDoctorEmailID.setText("Email ID");

        lblFirstName.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(0, 153, 255));
        lblFirstName.setText("First Name");

        lblEmailID.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblEmailID.setForeground(new java.awt.Color(0, 153, 255));
        lblEmailID.setText("Email ID");

        lblOwnerName.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblOwnerName.setForeground(new java.awt.Color(0, 153, 255));
        lblOwnerName.setText("Owner Name");

        txtOfficeAddress.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtOfficeAddress.setForeground(new java.awt.Color(0, 153, 255));
        txtOfficeAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOfficeAddressActionPerformed(evt);
            }
        });

        txtAddress1.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtAddress1.setForeground(new java.awt.Color(0, 153, 255));

        txtManufacturer.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtManufacturer.setForeground(new java.awt.Color(0, 153, 255));

        lblOfficeAddress.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblOfficeAddress.setForeground(new java.awt.Color(0, 153, 255));
        lblOfficeAddress.setText("Office Address");

        txtCity.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtCity.setForeground(new java.awt.Color(0, 153, 255));

        txtAddress2.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtAddress2.setForeground(new java.awt.Color(0, 153, 255));

        lblSpecialty.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblSpecialty.setForeground(new java.awt.Color(0, 153, 255));
        lblSpecialty.setText("Specialty");

        txtInsuranceCompany.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtInsuranceCompany.setForeground(new java.awt.Color(0, 153, 255));

        txtPremium.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtPremium.setForeground(new java.awt.Color(0, 153, 255));

        lblAddress1.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblAddress1.setForeground(new java.awt.Color(0, 153, 255));
        lblAddress1.setText("Address 1");

        txtLastName.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(0, 153, 255));
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });

        txtCompanyAddress.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtCompanyAddress.setForeground(new java.awt.Color(0, 153, 255));
        txtCompanyAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyAddressActionPerformed(evt);
            }
        });

        txtSpecialty.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtSpecialty.setForeground(new java.awt.Color(0, 153, 255));
        txtSpecialty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpecialtyActionPerformed(evt);
            }
        });

        lblMedicalSchool.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblMedicalSchool.setForeground(new java.awt.Color(0, 153, 255));
        lblMedicalSchool.setText("Medical School");

        lblBenefitsDesc.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblBenefitsDesc.setForeground(new java.awt.Color(0, 153, 255));
        lblBenefitsDesc.setText("Benefits Description");

        lblDoctorID.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblDoctorID.setForeground(new java.awt.Color(0, 153, 255));
        lblDoctorID.setText("Doctor ID");

        txtAllergies.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtAllergies.setForeground(new java.awt.Color(0, 153, 255));

        txtOnMedication.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtOnMedication.setForeground(new java.awt.Color(0, 153, 255));

        lblPatientReportTitle.setBackground(new java.awt.Color(255, 255, 51));
        lblPatientReportTitle.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblPatientReportTitle.setForeground(new java.awt.Color(0, 153, 255));
        lblPatientReportTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatientReportTitle.setText("Patient Report");

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportPanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOccupation)
                            .addComponent(lblGender)
                            .addComponent(lblDateOfBirth)
                            .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSSN)
                                    .addComponent(lblEmailID, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLastName)
                                    .addComponent(lblFirstName)))
                            .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPictureURL)
                                .addComponent(lblWebsiteURL)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPictureURL, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWebsiteURL, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblState)
                            .addComponent(lblCity)
                            .addComponent(lblAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCountry)
                            .addComponent(lblPinCode, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPinCode, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIssuingState)
                            .addComponent(txtdriverLicenseNumber)
                            .addComponent(lblDateOfExpiration)
                            .addComponent(lblOwnerName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDriverLicenseNumber)
                            .addComponent(txtIssuingState)
                            .addComponent(txtDateOfExpiration)
                            .addComponent(txtOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPatientID)
                            .addComponent(lblPatientName)
                            .addComponent(lblPrimaryDoctor)
                            .addComponent(lblDateOfLastVisit)
                            .addComponent(lblAllergies)
                            .addComponent(lblOnMedication))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPatientName)
                            .addComponent(txtPatientID)
                            .addComponent(txtPrimaryDoctor)
                            .addComponent(formattedDateOfLastVisit, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(txtAllergies)
                            .addComponent(txtOnMedication, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDoctorID)
                            .addComponent(lblDoctorName)
                            .addComponent(lblSpecialty)
                            .addComponent(lblOfficeAddress)
                            .addComponent(lblPhoneNumber1)
                            .addComponent(lblDoctorEmailID)
                            .addComponent(lblMedicalSchool)
                            .addComponent(lblDoctorGender))
                        .addGap(6, 6, 6)
                        .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDoctorID, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtSpecialty, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtOfficeAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtOfficePhoneNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDoctorEmailID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDoctorGender, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMedicalSchool, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(reportPanelLayout.createSequentialGroup()
                            .addComponent(lblVehicleModel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtVehicleModel, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(reportPanelLayout.createSequentialGroup()
                            .addComponent(lblManufacturer)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtManufacturer)))
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCorporateID)
                            .addComponent(lblInsuranceCompany)
                            .addComponent(lblCompanyAddress)
                            .addComponent(lblPremium)
                            .addComponent(lblDeductible)
                            .addComponent(lblBenefitsDesc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDeductible, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPremium, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCompanyAddress, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorporateID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInsuranceCompany, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(benefitsDescScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(99, 99, 99))
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(lblPatientReportTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        reportPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {benefitsDescScrollPane, formattedDateOfLastVisit, lblAddress1, lblAllergies, lblBenefitsDesc, lblCompanyAddress, lblCorporateID, lblDateOfBirth, lblDateOfLastVisit, lblDeductible, lblDoctorEmailID, lblDoctorGender, lblDoctorID, lblDoctorName, lblEmailID, lblFirstName, lblGender, lblInsuranceCompany, lblLastName, lblManufacturer, lblMedicalSchool, lblOccupation, lblOfficeAddress, lblOnMedication, lblPatientID, lblPatientName, lblPhoneNumber, lblPhoneNumber1, lblPictureURL, lblPremium, lblPrimaryDoctor, lblSSN, lblSpecialty, lblVehicleModel, lblWebsiteURL, txtAddress1, txtCompanyAddress, txtCorporateID, txtDateOfBirth, txtDeductible, txtDoctorEmailID, txtDoctorGender, txtDoctorID, txtDoctorName, txtEmailID, txtFirstName, txtGender, txtInsuranceCompany, txtLastName, txtManufacturer, txtMedicalSchool, txtOccupation, txtOfficeAddress, txtOfficePhoneNumber, txtPatientID, txtPatientName, txtPhoneNumber, txtPictureURL, txtPremium, txtPrimaryDoctor, txtSSN, txtSpecialty, txtVehicleModel, txtWebsiteURL});

        reportPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAddress2, lblCity, lblCountry, lblDateOfExpiration, lblIssuingState, lblOwnerName, lblPinCode, lblState, txtAddress2, txtCity, txtCountry, txtDateOfExpiration, txtDriverLicenseNumber, txtIssuingState, txtOwnerName, txtPinCode, txtState, txtdriverLicenseNumber});

        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblPatientReportTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSN)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailID)
                    .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoneNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDateOfBirth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOccupation)
                    .addComponent(txtOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWebsiteURL)
                    .addComponent(txtWebsiteURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPictureURL)
                    .addComponent(txtPictureURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress1)
                    .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress2)
                    .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblState)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPinCode)
                    .addComponent(txtPinCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCountry)
                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIssuingState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIssuingState)))
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdriverLicenseNumber)
                            .addComponent(txtDriverLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDateOfExpiration)
                            .addComponent(txtDateOfExpiration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOwnerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVehicleModel)
                    .addComponent(txtVehicleModel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacturer)
                    .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientName)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientID)
                    .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimaryDoctor)
                    .addComponent(txtPrimaryDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateOfLastVisit)
                    .addComponent(formattedDateOfLastVisit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAllergies)
                    .addComponent(txtAllergies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOnMedication)
                    .addComponent(txtOnMedication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorName)
                    .addComponent(txtDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorID)
                    .addComponent(txtDoctorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpecialty)
                    .addComponent(txtSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOfficeAddress)
                    .addComponent(txtOfficeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumber1)
                    .addComponent(txtOfficePhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorEmailID)
                    .addComponent(txtDoctorEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorGender)
                    .addComponent(txtDoctorGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicalSchool)
                    .addComponent(txtMedicalSchool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInsuranceCompany)
                    .addComponent(txtInsuranceCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorporateID)
                    .addComponent(txtCorporateID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompanyAddress)
                    .addComponent(txtCompanyAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPremium)
                    .addComponent(txtPremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeductible)
                    .addComponent(txtDeductible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBenefitsDesc)
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(benefitsDescScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        reportPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {formattedDateOfLastVisit, lblAddress1, lblAddress2, lblAllergies, lblCity, lblCompanyAddress, lblCorporateID, lblCountry, lblDateOfBirth, lblDateOfLastVisit, lblDeductible, lblDoctorEmailID, lblDoctorGender, lblDoctorID, lblDoctorName, lblEmailID, lblFirstName, lblGender, lblInsuranceCompany, lblIssuingState, lblLastName, lblManufacturer, lblMedicalSchool, lblOccupation, lblOfficeAddress, lblOnMedication, lblOwnerName, lblPatientID, lblPatientName, lblPhoneNumber, lblPhoneNumber1, lblPictureURL, lblPinCode, lblPremium, lblPrimaryDoctor, lblSSN, lblSpecialty, lblState, lblVehicleModel, lblWebsiteURL, txtAddress1, txtAddress2, txtCity, txtCompanyAddress, txtCorporateID, txtCountry, txtDateOfBirth, txtDeductible, txtDoctorEmailID, txtDoctorGender, txtDoctorID, txtDoctorName, txtEmailID, txtFirstName, txtGender, txtInsuranceCompany, txtLastName, txtManufacturer, txtMedicalSchool, txtOccupation, txtOfficeAddress, txtOfficePhoneNumber, txtOwnerName, txtPatientID, txtPatientName, txtPhoneNumber, txtPictureURL, txtPinCode, txtPremium, txtPrimaryDoctor, txtSSN, txtSpecialty, txtState, txtVehicleModel, txtWebsiteURL, txtdriverLicenseNumber});

        reportPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblDateOfExpiration, txtDateOfExpiration, txtDriverLicenseNumber, txtIssuingState});

        reportScrollPane.setViewportView(reportPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reportScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reportScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1659, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPictureURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPictureURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPictureURLActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtPinCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPinCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPinCodeActionPerformed

    private void txtStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateActionPerformed

    private void txtCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountryActionPerformed

    private void txtIssuingStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIssuingStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIssuingStateActionPerformed

    private void txtDateOfExpirationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateOfExpirationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateOfExpirationActionPerformed

    private void txtVehicleModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleModelActionPerformed

    private void txtPatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientIDActionPerformed

    private void txtPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientNameActionPerformed

    private void formattedDateOfLastVisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formattedDateOfLastVisitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedDateOfLastVisitActionPerformed

    private void txtOfficePhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOfficePhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOfficePhoneNumberActionPerformed

    private void txtOfficeAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOfficeAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOfficeAddressActionPerformed

    private void txtSpecialtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpecialtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpecialtyActionPerformed

    private void txtDoctorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorIDActionPerformed

    private void txtCompanyAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompanyAddressActionPerformed

    private void txtCorporateIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorporateIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorporateIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane benefitsDescScrollPane;
    private javax.swing.JFormattedTextField formattedDateOfLastVisit;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblAddress2;
    private javax.swing.JLabel lblAllergies;
    private javax.swing.JLabel lblBenefitsDesc;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCompanyAddress;
    private javax.swing.JLabel lblCorporateID;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblDateOfExpiration;
    private javax.swing.JLabel lblDateOfLastVisit;
    private javax.swing.JLabel lblDeductible;
    private javax.swing.JLabel lblDoctorEmailID;
    private javax.swing.JLabel lblDoctorGender;
    private javax.swing.JLabel lblDoctorID;
    private javax.swing.JLabel lblDoctorName;
    private javax.swing.JLabel lblEmailID;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblInsuranceCompany;
    private javax.swing.JLabel lblIssuingState;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblMedicalSchool;
    private javax.swing.JLabel lblOccupation;
    private javax.swing.JLabel lblOfficeAddress;
    private javax.swing.JLabel lblOnMedication;
    private javax.swing.JLabel lblOwnerName;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblPatientReportTitle;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhoneNumber1;
    private javax.swing.JLabel lblPictureURL;
    private javax.swing.JLabel lblPinCode;
    private javax.swing.JLabel lblPremium;
    private javax.swing.JLabel lblPrimaryDoctor;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblSpecialty;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblVehicleModel;
    private javax.swing.JLabel lblWebsiteURL;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JScrollPane reportScrollPane;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtAllergies;
    private javax.swing.JTextArea txtAreaBenefitsDesc;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCompanyAddress;
    private javax.swing.JTextField txtCorporateID;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtDateOfExpiration;
    private javax.swing.JTextField txtDeductible;
    private javax.swing.JTextField txtDoctorEmailID;
    private javax.swing.JTextField txtDoctorGender;
    private javax.swing.JTextField txtDoctorID;
    private javax.swing.JTextField txtDoctorName;
    private javax.swing.JTextField txtDriverLicenseNumber;
    private javax.swing.JTextField txtEmailID;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtInsuranceCompany;
    private javax.swing.JTextField txtIssuingState;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtManufacturer;
    private javax.swing.JTextField txtMedicalSchool;
    private javax.swing.JTextField txtOccupation;
    private javax.swing.JTextField txtOfficeAddress;
    private javax.swing.JTextField txtOfficePhoneNumber;
    private javax.swing.JTextField txtOnMedication;
    private javax.swing.JTextField txtOwnerName;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtPictureURL;
    private javax.swing.JTextField txtPinCode;
    private javax.swing.JTextField txtPremium;
    private javax.swing.JTextField txtPrimaryDoctor;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtSpecialty;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtVehicleModel;
    private javax.swing.JTextField txtWebsiteURL;
    private javax.swing.JLabel txtdriverLicenseNumber;
    // End of variables declaration//GEN-END:variables

    private void displayPerson() {
        System.out.println("First Name: "+ person.getFirstName());
        System.out.println("Last Name: "+ person.getLastName());
        System.out.println("Social Security Number: "+ person.getSsn());
        System.out.println("EmailID: "+ person.getEmailID());
        System.out.println("Phone Number: "+ person.getPhoneNumber());
        System.out.println("Date Of Birth: "+ person.getDateOfBirth());
        System.out.println("Gender: "+ person.getGender());
        System.out.println("Occupation: "+ person.getOccupation());
        System.out.println("Website URL: "+ person.getWebsiteURL());
        System.out.println("Picture URL: "+ person.getPictureURL());
       
        txtFirstName.setText(person.getFirstName());
        txtLastName.setText(person.getLastName());
        txtSSN.setText(person.getSsn());
        txtEmailID.setText(person.getEmailID());
        txtPhoneNumber.setText(person.getPhoneNumber());
        txtDateOfBirth.setText(person.getDateOfBirth());
        txtGender.setText(person.getGender());
        txtOccupation.setText(person.getOccupation());
        txtWebsiteURL.setText(person.getWebsiteURL());
        txtPictureURL.setText(person.getPictureURL());  
    }

    private void displayAddress() {
        System.out.println("Address 1: " +address.getAddress1());
        System.out.println("Address 2: " +address.getAddress2());
        System.out.println("City: " +address.getCity());
        System.out.println("State: " +address.getState());
        System.out.println("Pin Code: " +address.getPinCode());
        System.out.println("Country: " +address.getCountry());
        
        txtAddress1.setText(address.getAddress1());
        txtAddress2.setText(address.getAddress2());
        txtCity.setText(address.getCity());
        txtState.setText(address.getState());
        txtPinCode.setText(address.getPinCode());
        txtCountry.setText(address.getCountry());   
    }

    private void displayDriver() {
        System.out.println("Driver License Number: " +driver.getDriverLicenseNumber());
        System.out.println("Issuing State: " +driver.getIssuingState());
        System.out.println("Date Of Expiration: " +driver.getDateOfExpiration());
        
        txtDriverLicenseNumber.setText(driver.getDriverLicenseNumber());
        txtIssuingState.setText(driver.getIssuingState());
        txtDateOfExpiration.setText(driver.getDateOfExpiration()); 
    }

    private void displayVehicleRegistration() {
        System.out.println("Owner Name: "+ vehicleRegistration.getOwnerName());
        System.out.println("Vehicle Model: "+ vehicleRegistration.getVehicleModel());
        System.out.println("Manufacturer: "+ vehicleRegistration.getManufacturer());
        
        
        txtOwnerName.setText(vehicleRegistration.getOwnerName());
        txtVehicleModel.setText(vehicleRegistration.getVehicleModel());
        txtManufacturer.setText(vehicleRegistration.getManufacturer());   
    }

    private void displayPatient() {  
        System.out.println("Patient Name: "+ patient.getPatientName());
        System.out.println("Patient ID: "+ patient.getPatientID());
        System.out.println("Primary Doctor: "+ patient.getPrimaryDoctor()); 
        System.out.println("Date of Last Visit: "+ formattedDateOfLastVisit.getText()); 
       
        String hasAllergies = patient.getAllergies()? "Yes" : "No";
        System.out.println("Allergies: "+ hasAllergies);
        
        String isOnMedication = patient.getOnMedication()? "Yes" : "No";
        System.out.println("On Medication: "+ isOnMedication);
   
        txtPatientName.setText(patient.getPatientName());
        txtPatientID.setText(patient.getPatientID());
        txtPrimaryDoctor.setText(patient.getPrimaryDoctor());
        formattedDateOfLastVisit.setText(patient.getDateOfLastVisit());
        txtAllergies.setText(patient.getAllergies()? "Yes" : "No");
        txtOnMedication.setText(patient.getOnMedication()? "Yes" : "No");
    }

    private void displayDoctor() {
        
        System.out.println("Doctor Name: " +doctor.getDoctorName());    
        System.out.println("Doctor ID: " +doctor.getDoctorID());     
        System.out.println("Specialty: " +doctor.getSpecialty());     
        System.out.println("Office Address: " +doctor.getOfficeAddress());     
        System.out.println("Office Phone Number: " +doctor.getOfficePhoneNumber()); 
        System.out.println("Email ID: " +doctor.getDoctorEmail());   
        System.out.println("Office Address: " +doctor.getDoctorGender());     
        System.out.println("Medical School: " +doctor.getMedicalSchool());
        
        txtDoctorName.setText(doctor.getDoctorName());
        txtDoctorID.setText(doctor.getDoctorID());
        txtSpecialty.setText(doctor.getSpecialty());
        txtOfficeAddress.setText(doctor.getOfficeAddress());
        txtOfficePhoneNumber.setText(doctor.getOfficePhoneNumber());
        txtDoctorEmailID.setText(doctor.getDoctorEmail());
        txtDoctorGender.setText(doctor.getDoctorGender());
        txtMedicalSchool.setText(doctor.getMedicalSchool());
    }

    private void displayInsuranceCoverage() {
        double premiumAmount = insuranceCoverage.getPremiumAmount();
        double deductibleAmount = insuranceCoverage.getDeductibleAmount();
        String benefitsDescription;
        benefitsDescription = insuranceCoverage.getBenefitsDescription();
        
        System.out.println("Insurance Company: " +insuranceCoverage.getInsuranceCompany());
        System.out.println("Corporate ID: " +insuranceCoverage.getCorporateID());
        System.out.println("Company Address: " +insuranceCoverage.getInsuranceAddress());
        System.out.println("Premium Amount($): " +premiumAmount);
        System.out.println("Deductible Amount($): " +deductibleAmount);
        System.out.println("Benefits Description: " +benefitsDescription);
        
        txtInsuranceCompany.setText(insuranceCoverage.getInsuranceCompany());
        txtCorporateID.setText(insuranceCoverage.getCorporateID());
        txtCompanyAddress.setText(insuranceCoverage.getInsuranceAddress());
        txtPremium.setText(String.valueOf(premiumAmount));
        txtDeductible.setText(String.valueOf(deductibleAmount));
        txtAreaBenefitsDesc.setText(benefitsDescription);   
    }
}
