/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.Patient;

/**
 *
 * @author kamuni.saheeshna
 */
public class PatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientJPanel
     */
    Patient patient;
    public PatientJPanel(Patient patient) {
        initComponents();
        this.patient = patient;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientScrollPane = new javax.swing.JScrollPane();
        patientPanel = new javax.swing.JPanel();
        txtPatientName = new javax.swing.JTextField();
        btnPatientSave = new javax.swing.JButton();
        lblDateOfLastVisit = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        lblPatientID = new javax.swing.JLabel();
        txtPrimaryDoctor = new javax.swing.JTextField();
        lblPrimaryDoctor = new javax.swing.JLabel();
        formattedDateOfLastVisit = new javax.swing.JFormattedTextField();
        lblAllergies = new javax.swing.JLabel();
        lblOnMedication = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        lblPatientTitle = new javax.swing.JLabel();
        radioAllergies = new javax.swing.JRadioButton();
        radioOnMedication = new javax.swing.JRadioButton();

        patientPanel.setBackground(new java.awt.Color(204, 255, 51));

        txtPatientName.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtPatientName.setForeground(new java.awt.Color(0, 153, 153));
        txtPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientNameActionPerformed(evt);
            }
        });

        btnPatientSave.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        btnPatientSave.setForeground(new java.awt.Color(0, 153, 153));
        btnPatientSave.setText("Save");
        btnPatientSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPatientSave.setBorderPainted(false);
        btnPatientSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientSaveActionPerformed(evt);
            }
        });

        lblDateOfLastVisit.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblDateOfLastVisit.setForeground(new java.awt.Color(0, 153, 153));
        lblDateOfLastVisit.setText("Date Of Last Visit");

        lblPatientName.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblPatientName.setForeground(new java.awt.Color(0, 153, 153));
        lblPatientName.setText("Patient Name");

        lblPatientID.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblPatientID.setForeground(new java.awt.Color(0, 153, 153));
        lblPatientID.setText("Patient ID");

        txtPrimaryDoctor.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtPrimaryDoctor.setForeground(new java.awt.Color(0, 153, 153));

        lblPrimaryDoctor.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblPrimaryDoctor.setForeground(new java.awt.Color(0, 153, 153));
        lblPrimaryDoctor.setText("Primary Doctor");

        formattedDateOfLastVisit.setForeground(new java.awt.Color(0, 153, 153));
        formattedDateOfLastVisit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formattedDateOfLastVisitActionPerformed(evt);
            }
        });

        lblAllergies.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblAllergies.setForeground(new java.awt.Color(0, 153, 153));
        lblAllergies.setText("Allergies");

        lblOnMedication.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblOnMedication.setForeground(new java.awt.Color(0, 153, 153));
        lblOnMedication.setText("On Medication");

        txtPatientID.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtPatientID.setForeground(new java.awt.Color(0, 153, 153));
        txtPatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientIDActionPerformed(evt);
            }
        });

        lblPatientTitle.setFont(new java.awt.Font("Book Antiqua", 3, 24)); // NOI18N
        lblPatientTitle.setForeground(new java.awt.Color(0, 153, 153));
        lblPatientTitle.setText("Patient Details");

        radioOnMedication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioOnMedicationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout patientPanelLayout = new javax.swing.GroupLayout(patientPanel);
        patientPanel.setLayout(patientPanelLayout);
        patientPanelLayout.setHorizontalGroup(
            patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientPanelLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(patientPanelLayout.createSequentialGroup()
                            .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblPatientID)
                                .addComponent(lblPatientName)
                                .addComponent(lblPrimaryDoctor)
                                .addComponent(lblDateOfLastVisit)
                                .addComponent(lblAllergies)
                                .addComponent(lblOnMedication))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPrimaryDoctor)
                                .addComponent(formattedDateOfLastVisit)
                                .addComponent(txtPatientName, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(txtPatientID)
                                .addComponent(radioAllergies)
                                .addComponent(radioOnMedication)))
                        .addGroup(patientPanelLayout.createSequentialGroup()
                            .addGap(83, 83, 83)
                            .addComponent(btnPatientSave)))
                    .addGroup(patientPanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblPatientTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(334, Short.MAX_VALUE))
        );

        patientPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnPatientSave, formattedDateOfLastVisit, lblAllergies, lblDateOfLastVisit, lblOnMedication, lblPatientID, lblPatientName, lblPatientTitle, lblPrimaryDoctor, txtPatientID, txtPatientName, txtPrimaryDoctor});

        patientPanelLayout.setVerticalGroup(
            patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lblPatientTitle)
                .addGap(27, 27, 27)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientName)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientID)
                    .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimaryDoctor)
                    .addComponent(txtPrimaryDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateOfLastVisit)
                    .addComponent(formattedDateOfLastVisit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAllergies)
                    .addComponent(radioAllergies))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOnMedication)
                    .addComponent(radioOnMedication))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPatientSave)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        patientPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnPatientSave, formattedDateOfLastVisit, lblAllergies, lblDateOfLastVisit, lblOnMedication, lblPatientID, lblPatientName, lblPatientTitle, lblPrimaryDoctor, txtPatientID, txtPatientName, txtPrimaryDoctor});

        patientScrollPane.setViewportView(patientPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formattedDateOfLastVisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formattedDateOfLastVisitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedDateOfLastVisitActionPerformed

    private void txtPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientNameActionPerformed

    private void txtPatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientIDActionPerformed

    private void btnPatientSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientSaveActionPerformed
        // TODO add your handling code here:
        patient.setPatientName(txtPatientName.getText());
        patient.setPatientID(txtPatientID.getText());
        patient.setPrimaryDoctor(txtPrimaryDoctor.getText());
        patient.setDateOfLastVisit(formattedDateOfLastVisit.getText());
        
        boolean hasAllergies = radioAllergies.isSelected();    
        patient.setAllergies(hasAllergies);
        
        boolean isOnMedication = radioOnMedication.isSelected();        
        patient.setOnMedication(isOnMedication);
        
        JOptionPane.showMessageDialog(this,"Patient Details Saved");
    }//GEN-LAST:event_btnPatientSaveActionPerformed

    private void radioOnMedicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioOnMedicationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioOnMedicationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPatientSave;
    private javax.swing.JFormattedTextField formattedDateOfLastVisit;
    private javax.swing.JLabel lblAllergies;
    private javax.swing.JLabel lblDateOfLastVisit;
    private javax.swing.JLabel lblOnMedication;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblPatientTitle;
    private javax.swing.JLabel lblPrimaryDoctor;
    private javax.swing.JPanel patientPanel;
    private javax.swing.JScrollPane patientScrollPane;
    private javax.swing.JRadioButton radioAllergies;
    private javax.swing.JRadioButton radioOnMedication;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPrimaryDoctor;
    // End of variables declaration//GEN-END:variables
}
