/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import model.Person;

/**
 *
 * @author kamuni.saheeshna
 */
public class PersonJPanel extends javax.swing.JPanel {
    
    Person person;

    /**
     * Creates new form PersonJPanel
     * @param person
     */
    public PersonJPanel(Person person) {
        initComponents();
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personScrollPanel = new javax.swing.JScrollPane();
        personPanel = new javax.swing.JPanel();
        lblLastName = new javax.swing.JLabel();
        txtPictureURL = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        lblWebsiteURL = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        lblPhoneNumber = new javax.swing.JLabel();
        txtWebsiteURL = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblDateOfBirth = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblEmailID = new javax.swing.JLabel();
        lblOccupation = new javax.swing.JLabel();
        txtEmailID = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        txtOccupation = new javax.swing.JTextField();
        lblPictureURL = new javax.swing.JLabel();
        txtDateOfBirth = new javax.swing.JTextField();
        btnPersonSave = new javax.swing.JButton();

        personPanel.setBackground(new java.awt.Color(204, 255, 255));
        personPanel.setForeground(new java.awt.Color(255, 255, 204));

        lblLastName.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(51, 51, 255));
        lblLastName.setText("Last Name");

        txtPictureURL.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtPictureURL.setForeground(new java.awt.Color(51, 51, 255));
        txtPictureURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPictureURLActionPerformed(evt);
            }
        });

        txtLastName.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(51, 51, 255));
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });

        lblWebsiteURL.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblWebsiteURL.setForeground(new java.awt.Color(51, 51, 255));
        lblWebsiteURL.setText("Website URL");

        txtFirstName.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtFirstName.setForeground(new java.awt.Color(51, 51, 255));

        txtPhoneNumber.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtPhoneNumber.setForeground(new java.awt.Color(51, 51, 255));
        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });

        lblGender.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblGender.setForeground(new java.awt.Color(51, 51, 255));
        lblGender.setText("Gender");

        txtGender.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtGender.setForeground(new java.awt.Color(51, 51, 255));

        lblPhoneNumber.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(51, 51, 255));
        lblPhoneNumber.setText("Phone Number");

        txtWebsiteURL.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtWebsiteURL.setForeground(new java.awt.Color(51, 51, 255));

        txtSSN.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtSSN.setForeground(new java.awt.Color(51, 51, 255));
        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Book Antiqua", 3, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(51, 51, 255));
        lblTitle.setText("Personal Details");

        lblDateOfBirth.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblDateOfBirth.setForeground(new java.awt.Color(51, 51, 255));
        lblDateOfBirth.setText("Date Of Birth");

        lblFirstName.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(51, 51, 255));
        lblFirstName.setText("First Name");

        lblEmailID.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblEmailID.setForeground(new java.awt.Color(51, 51, 255));
        lblEmailID.setText("Email ID");

        lblOccupation.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblOccupation.setForeground(new java.awt.Color(51, 51, 255));
        lblOccupation.setText("Occupation");

        txtEmailID.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtEmailID.setForeground(new java.awt.Color(51, 51, 255));

        lblSSN.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblSSN.setForeground(new java.awt.Color(51, 51, 255));
        lblSSN.setText("Social Security Number");

        txtOccupation.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtOccupation.setForeground(new java.awt.Color(51, 51, 255));

        lblPictureURL.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblPictureURL.setForeground(new java.awt.Color(51, 51, 255));
        lblPictureURL.setText("Picture URL");

        txtDateOfBirth.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtDateOfBirth.setForeground(new java.awt.Color(51, 51, 255));

        btnPersonSave.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        btnPersonSave.setForeground(new java.awt.Color(51, 51, 255));
        btnPersonSave.setText("Save");
        btnPersonSave.setBorderPainted(false);
        btnPersonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout personPanelLayout = new javax.swing.GroupLayout(personPanel);
        personPanel.setLayout(personPanelLayout);
        personPanelLayout.setHorizontalGroup(
            personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personPanelLayout.createSequentialGroup()
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personPanelLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personPanelLayout.createSequentialGroup()
                                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblOccupation)
                                    .addComponent(lblGender)
                                    .addComponent(lblDateOfBirth)
                                    .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSSN)
                                            .addComponent(lblEmailID, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblLastName)
                                            .addComponent(lblFirstName)))
                                    .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblPictureURL)
                                        .addComponent(lblWebsiteURL)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWebsiteURL, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPictureURL, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(personPanelLayout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(lblTitle))))
                    .addGroup(personPanelLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(btnPersonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(265, Short.MAX_VALUE))
        );

        personPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblDateOfBirth, lblEmailID, lblFirstName, lblGender, lblLastName, lblOccupation, lblPhoneNumber, lblPictureURL, lblSSN, lblWebsiteURL, txtDateOfBirth, txtEmailID, txtFirstName, txtGender, txtLastName, txtOccupation, txtPhoneNumber, txtPictureURL, txtSSN, txtWebsiteURL});

        personPanelLayout.setVerticalGroup(
            personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSN)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailID)
                    .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoneNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDateOfBirth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOccupation)
                    .addComponent(txtOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWebsiteURL)
                    .addComponent(txtWebsiteURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPictureURL)
                    .addComponent(txtPictureURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPersonSave)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        personPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblDateOfBirth, lblEmailID, lblFirstName, lblGender, lblLastName, lblOccupation, lblPhoneNumber, lblPictureURL, lblSSN, lblWebsiteURL, txtDateOfBirth, txtEmailID, txtFirstName, txtGender, txtLastName, txtOccupation, txtPhoneNumber, txtPictureURL, txtSSN, txtWebsiteURL});

        personScrollPanel.setViewportView(personPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(personScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(personScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void txtPictureURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPictureURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPictureURLActionPerformed

    private void btnPersonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonSaveActionPerformed
        // TODO add your handling code here:
        person.setFirstName(txtFirstName.getText());
        person.setLastName(txtLastName.getText());
        person.setSsn(txtSSN.getText());
        person.setEmailID(txtEmailID.getText());
        person.setPhoneNumber(txtPhoneNumber.getText());
        person.setDateOfBirth(txtDateOfBirth.getText());
        person.setGender(txtGender.getText());
        person.setOccupation(txtOccupation.getText());
        person.setWebsiteURL(txtWebsiteURL.getText());
        person.setPictureURL(txtPictureURL.getText());
       
      
        Font customFont = new Font("Book Antiqua", Font.BOLD | Font.ITALIC, 16);
        UIManager.put("OptionPane.messageFont", customFont);
        UIManager.put("OptionPane.buttonFont", customFont);
        UIManager.put("OptionPane.background",new Color(255, 153, 204));
        UIManager.put("OptionPane.messageForeground",new Color(51, 0, 102));
        
        JOptionPane.showMessageDialog(this, "Personal Details Saved");
        
        
        
    }//GEN-LAST:event_btnPersonSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPersonSave;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblEmailID;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblOccupation;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPictureURL;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWebsiteURL;
    private javax.swing.JPanel personPanel;
    private javax.swing.JScrollPane personScrollPanel;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtEmailID;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtOccupation;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtPictureURL;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtWebsiteURL;
    // End of variables declaration//GEN-END:variables
}
