/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.VehicleRegistration;

/**
 *
 * @author kamuni.saheeshna
 */
public class VehicleRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VehicleRegistrationJPanel
     */
    VehicleRegistration vehicleRegistration;
    public VehicleRegistrationJPanel(VehicleRegistration vehicleRegistration) {
        initComponents();
        this.vehicleRegistration = vehicleRegistration;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vehicleRegistrationScrollPane = new javax.swing.JScrollPane();
        vehicleRegistrationPanel = new javax.swing.JPanel();
        lblVehicleRegisTitle = new javax.swing.JLabel();
        lblManufacturer = new javax.swing.JLabel();
        lblOwnerName = new javax.swing.JLabel();
        txtManufacturer = new javax.swing.JTextField();
        btnVehicleRegistrationSave = new javax.swing.JButton();
        txtOwnerName = new javax.swing.JTextField();
        lblVehicleModel = new javax.swing.JLabel();
        txtVehicleModel = new javax.swing.JTextField();

        vehicleRegistrationPanel.setBackground(new java.awt.Color(255, 255, 0));

        lblVehicleRegisTitle.setFont(new java.awt.Font("Book Antiqua", 3, 24)); // NOI18N
        lblVehicleRegisTitle.setForeground(new java.awt.Color(153, 0, 153));
        lblVehicleRegisTitle.setText("Vehicle Registration Form");

        lblManufacturer.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblManufacturer.setForeground(new java.awt.Color(153, 0, 153));
        lblManufacturer.setText("Manufacturer");

        lblOwnerName.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblOwnerName.setForeground(new java.awt.Color(153, 0, 153));
        lblOwnerName.setText("Owner Name");

        txtManufacturer.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtManufacturer.setForeground(new java.awt.Color(153, 0, 153));
        txtManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufacturerActionPerformed(evt);
            }
        });

        btnVehicleRegistrationSave.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        btnVehicleRegistrationSave.setForeground(new java.awt.Color(153, 0, 153));
        btnVehicleRegistrationSave.setText("Save");
        btnVehicleRegistrationSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVehicleRegistrationSave.setBorderPainted(false);
        btnVehicleRegistrationSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehicleRegistrationSaveActionPerformed(evt);
            }
        });

        txtOwnerName.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtOwnerName.setForeground(new java.awt.Color(153, 0, 153));

        lblVehicleModel.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblVehicleModel.setForeground(new java.awt.Color(153, 0, 153));
        lblVehicleModel.setText("Vehicle Model");

        txtVehicleModel.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        txtVehicleModel.setForeground(new java.awt.Color(153, 0, 153));
        txtVehicleModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleModelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vehicleRegistrationPanelLayout = new javax.swing.GroupLayout(vehicleRegistrationPanel);
        vehicleRegistrationPanel.setLayout(vehicleRegistrationPanelLayout);
        vehicleRegistrationPanelLayout.setHorizontalGroup(
            vehicleRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicleRegistrationPanelLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(vehicleRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vehicleRegistrationPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblVehicleRegisTitle))
                    .addGroup(vehicleRegistrationPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnVehicleRegistrationSave))
                    .addGroup(vehicleRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(vehicleRegistrationPanelLayout.createSequentialGroup()
                            .addComponent(lblManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtManufacturer, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                        .addGroup(vehicleRegistrationPanelLayout.createSequentialGroup()
                            .addGroup(vehicleRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblVehicleModel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(48, 48, 48)
                            .addGroup(vehicleRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtOwnerName)
                                .addComponent(txtVehicleModel, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)))))
                .addContainerGap(371, Short.MAX_VALUE))
        );

        vehicleRegistrationPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnVehicleRegistrationSave, lblVehicleRegisTitle, txtManufacturer, txtOwnerName, txtVehicleModel});

        vehicleRegistrationPanelLayout.setVerticalGroup(
            vehicleRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicleRegistrationPanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(lblVehicleRegisTitle)
                .addGap(21, 21, 21)
                .addGroup(vehicleRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOwnerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vehicleRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVehicleModel)
                    .addComponent(txtVehicleModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vehicleRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManufacturer)
                    .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVehicleRegistrationSave)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        vehicleRegistrationPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnVehicleRegistrationSave, lblManufacturer, lblOwnerName, lblVehicleModel, lblVehicleRegisTitle, txtManufacturer, txtOwnerName, txtVehicleModel});

        vehicleRegistrationScrollPane.setViewportView(vehicleRegistrationPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(vehicleRegistrationScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vehicleRegistrationScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtVehicleModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleModelActionPerformed

    private void btnVehicleRegistrationSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehicleRegistrationSaveActionPerformed
        // TODO add your handling code here:
        vehicleRegistration.setOwnerName(txtOwnerName.getText());
        vehicleRegistration.setVehicleModel(txtVehicleModel.getText());
        vehicleRegistration.setManufacturer(txtManufacturer.getText());
                
        JOptionPane.showMessageDialog(this,"Vehicle Registration Information Saved");
        
    }//GEN-LAST:event_btnVehicleRegistrationSaveActionPerformed

    private void txtManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufacturerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufacturerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVehicleRegistrationSave;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblOwnerName;
    private javax.swing.JLabel lblVehicleModel;
    private javax.swing.JLabel lblVehicleRegisTitle;
    private javax.swing.JTextField txtManufacturer;
    private javax.swing.JTextField txtOwnerName;
    private javax.swing.JTextField txtVehicleModel;
    private javax.swing.JPanel vehicleRegistrationPanel;
    private javax.swing.JScrollPane vehicleRegistrationScrollPane;
    // End of variables declaration//GEN-END:variables
}
